### PR TITLE
Salty Livery

### PR DESCRIPTION
**Pull request by dcherrie**
Salty Livery

### CODE REVIEW

**Comment by Cronch** [comment]
@dcherrie could you share some screenshots to check this livery?

**Comment by giridat** [comment]
@dcherrie is this still WIP?

**Comment by dcherrie** [comment]
@giridat negative, this is complete and official.

Salty Image 1

Salty Image 2

Salty Image 3

**Comment by DesertRick13** [comment]
sweet!

**Comment by DesertRick13** [comment]
When will this be available?

**Comment by DesertRick13** [comment]
Is this going to be merged into a dev version? Will it be available as a standalone like other liveries of yours? please advise.

**Pull request closed without merging**
