### PR TITLE
Brightness fixes

### PR DESCRIPTION
**Pull request by chloe1192**
- [x] FMC Brightness not dimmed by the AISLE STAND
- [x] SEAT BELT dimmed by AISLE STAND
- [x] Rudder Screen dimmed by AISLE STAND
- [x] IRS knob dimmed by OVHD PANEL
- [x] FUEL JETTINSON dimmed by OVHD PANEL

### CODE REVIEW

**Review by ninjomcs — CHANGES_REQUESTED** [review]
could you base this on the new model xmls?

**Comment by chloe1192** [comment]
> could you base this on the new model xmls?

Partially done

**Comment by 747-4EVER** [comment]
Can you confirm if this is ready to merge?

**Comment by chloe1192** [comment]
> Can you confirm if this is ready to merge?

I create another PR, this one was too hard to save. The other one is ready to mege

**Pull request closed without merging**
