### PR TITLE
Fixes Parking Brake EICAS Message

### PR DESCRIPTION
**Pull request by chloe1192**
Fixes issue #98 
Changed message to PARK BRAKE SET and type to Advisory.

### CODE REVIEW

**Review by ninjomcs — APPROVED** [review]

**Comment by airifr** [comment]
PARK BRAKE SET type is MEMO not advisory, in white on EICAS.
IMG_20201212_102411

**Comment by ninjomcs** [comment]
I’m pretty sure Asobo only implemented Warning and Advisory types, which is why we need a rewrite it.

**Comment by chloe1192** [comment]
There's only Warning, Caution and Advisory. But advisory messages are displayed in white. I'll post the screenshot.

**Comment by chloe1192** [comment]
Screenshot (260)

**Comment by chloe1192** [comment]
I could rewrite the EICAS Messages logic, but i'll wait for the sim update to see if Asobo doesn't change it.

**Comment by 747-4EVER** [comment]
Quite a big task, there's fairly complex logic with the message prioritisation, multiple pages of messages, recall function etc

Better to have the basic messages available for now at least in the interim, I would think.

**Comment by airifr** [comment]
This is correct, sorry for the misleading, MEMO are advisory alright, in white. I used those two interchangeably.. Your pic is not correct, (I use memo for short) MEMO messages are in the MEMO group box, not in the WARNING CAUTION group box, see pic.
IMG_20201212_112256

**Comment by chloe1192** [comment]
> 
> 
> This is correct, sorry for the misleading, MEMO are advisory alright, in white. I used those two interchangeably.. Your pic is not correct, (I use memo for short) MEMO messages are in the MEMO group box, not in the WARNING CAUTION group box, see pic.
> IMG_20201212_112256
I'll see if i can create another message class without, but i'm not sure it'll work.

**Comment by chloe1192** [comment]
> 
> 
> This is correct, sorry for the misleading, MEMO are advisory alright, in white. I used those two interchangeably.. Your pic is not correct, (I use memo for short) MEMO messages are in the MEMO group box, not in the WARNING CAUTION group box, see pic.
> IMG_20201212_112256

I'll see if i can create another message class.

**Comment by chloe1192** [comment]
> 
> 
> Quite a big task, there's fairly complex logic with the message prioritisation, multiple pages of messages, recall function etc
> 
> Better to have the basic messages available for now at least in the interim, I would think.

I agree.

**Comment by 747-4EVER** [comment]
> > This is correct, sorry for the misleading, MEMO are advisory alright, in white. I used those two interchangeably.. Your pic is not correct, (I use memo for short) MEMO messages are in the MEMO group box, not in the WARNING CAUTION group box, see pic.
> > IMG_20201212_112256
> 
> I'll see if i can create another message class.

You are correct the memo messages occupy their own space on the lower part of the EICAS, however we cannot just draw them on the display independently as the priority system will push them off if there are too many Warning/Caution/Advisories.

To do it properly at the moment is beyond the scope of Asobo's current implementation without major rework unfortunately.

**Comment by airifr** [comment]
Alright.
At least we'd have proper white PARK BRAKE SET shown on EICAS in the meantime, thank you.

**Comment by neshk16** [comment]
Just spawned in, it works.

**Pull request merged**
