### PR TITLE
Engine Performance Tuning

### LINKED ISSUE #106: [BUG] Low Fuel Consumption
**Version of the mod**
Latest development mod at time of post.

**Describe the bug**
The plane does not consume anywhere near the amount of fuel that it should be according to Simbrief.

**To Reproduce**
1. Use Simbrief for a flight using the 747-8 aircraft.
2. Over time, fuel burn isn't as realistic as what Simbrief predicts.

**Expected behavior**
Higher rate of fuel consumption closer to that of a Simbrief flight.

**Screenshots**
Have attached Simbrief with updated on-route fuel updates.
[YSSYKJFK_PDF_10Dec20.pdf](https://github.com/saltysimulations/salty-747/files/5676382/YSSYKJFK_PDF_10Dec20.pdf)

**References**
Currently flying from YSSY to KJFK which is a flight that a 747-8 shouldn't be able to make with a regular payload. After flying for about 13 hours now Simbrief says I should have about 93.6 thousand pounds of fuel, instead I have 241.4 thousand pounds left.

Currently with this fuel consumption, I think I'd be able to circumnavigate the globe on one tank of fuel.

**Additional information**
Is this bug present in the default 747-8, or only in the mod?

Your Discord: davidcherrie#1672

### PR DESCRIPTION
**Pull request by 747-4EVER**
Engine Performance Tuning
----------------------------------------------------------------------------
Objective to tune the engine performance and correct overpowered engine thrust causing:

- Grossly inaccurate fuel burn (Too low).

- Unrealistically low N1 in cruise.

- Aircraft capable of far exceeding realistic maximum flight levels.

- Very short takeoff runs even at maximum weight

**Changes:**
----------------------------------------------------------------------------
- Adjusted Engine Thrust Scalar

- Adjusted Fuel Flow Scalar

- Fixed bug causing fuel flow meter to show KGs when all other indications were in LBs.
 ----------------------------------------------------------------------------

Target Climb performance:
image

Target Cruise Ceilings:
image

Target Cruise N1:
image

----------------------------------------------------------------------------

**Notes to Dev Team/QA:**
The above values are ideal targets, in most cases the aircraft will not achieve these exactly. The aim of these changes for now is to remove the gross error currently present in the flight model.

- N1 Values will still be slightly too low, but to reduce thrust further will result in unacceptable climb performance, so a compromise had to be reached.

- Fuel flow has been fine tuned to approximate SimBrief estimates (Approx 20000lb/Hr average fuel flow at FL360 M.86)
I achieved about a 1.6% error (1800Lbs) on arrival fuel after a 6 hour test flight vs Simbrief zero wind FPL (More data from QA would be appreciated to refine further)

- Now with the reduced engine thrust, you may have problems on Auto-Throttle with climb rate approaching cruise altitude. This is due to incorrect autothrottle behaviour limiting your thrust available. Disconnecting and manually setting the levers forward or selecting full CLB in the FMC Thrust Limit page will result in acceptable climb performance. I will look into fixing this in the near future, time permitting.

Fixes #106

### CODE REVIEW

**Review by ninjomcs — APPROVED** [review]

**Comment by tariq-a** [comment]
I used this on several flights over the last month and this was working really well until the UK update, however after the update the engines no longer seem powerful enough (this is after halving `lift_coef_flaps` in the current flight model).

The main pain points are:
- Takeoff distance seems too long now
- VNAV climb rate with flaps 1 seems too low (less than 1k fpm)

I've noticed that if you halve the `drag_coef_flaps` in the flight model then the performance seems much closer to what it was before the UK update.

**Comment by tariq-a** [comment]
Name: Tariq #4753
Date of testing: 27/02/2021
Version of the sim: 1.13.16.0
PR Tested: #131

Testing technique: Carried out a full flight planned using simbrief and took notes on climb performance. The flight was also tracked with sim toolkit pro.

Steps you've made to test the Pull Request:

1. Manually changed flight_model.cfg to have `lift_coef_flaps` of `0.5581`
1. Setup a flight using simbrief from EDDF to EGKK with M86 cruise profile, 651.0 klb ZFW
1. Setup the aircraft, input the flightplan. 59.0 klb total fuel and 715.9 klb gross weight at gate
1. Set flaps 20 takeoff configuration, V1 was 121, VR was 136, V2 was 154
1. Set full power takeoff and climb thrust limits
1. LNAV and VNAV were used throughout the climb
1. Retracted flaps as per schedule, kept flaps 1 until 10,000
1. Climb was at 250 kias, flaps 1 until 10,000. The initial climb rate was 1300 FPM, reducing to around 700 FPM at 7000 and then 500 FPM near 9000
1. At 10,000 accelerated to 310 kias, flaps fully retracted
1. Climb performance afterwards was as follows:

| Altitude (FL) | Speed (KIAS or M) | Vertical Speed (FPM) |
| ----------- | ----------- | ----------- |
| 120 | 310 | 2700 |
| 180 | 310 | 2300 |
| 180 | 310 | 2300 |
| 200 | 310 | 1800 |
| 240 | 310 | 1300 |
| 280 | 310 | 1000 |
| 300 | 310 | 900 |
| 320 | 0.82 | 1200 |
| 340 | 0.82 | 1000 |

11. Cruised at FL360, 0.86 mach. N1 averaged 82.5 and FF averaged 5.2 on each engine
11. Arrived at EGKK, total trip distance was 339 nm / 1h31m of flight time and 22,000 lb of fuel was consumed. Simbrief had predicted 24,493 lb for the trip.

Overall Rating: Good with some minor issues

Conclusions of the testing:

- The takeoff distance seems okay with regular TO thrust limit set and no derate
- The fuel consumption is much improved
- Climb performance with flaps 1 above 7000 feet is quite bad, not sure how realistic it is. I think the easiest way of improve it would be to reduce `drag_coef_flaps` slightly but that needs to be balanced so as not to impact takeoff and landing performance too much.
- Climb performance with flaps retracted seems acceptable until FL280 where it's a bit too low. VNAV seems to switch to M0.82 at around FL300 which helps with the rest of the climb.

**Comment by dcherrie** [comment]
@747-4EVER I'm guessing this hasn't been committed to the master yet? I've just been doing tests and calculating the error of fuel burn over long haul flights and am finding a 35-45% error. I just did a 90 minute flight and 13.5 hour flight with the fuel_flow_scalar set to 1.12 instead of 0.8 and got a much more realistic fuel burn (although going faster than ECON). Has been the first time flying the 747-8 long haul without having to dump 150,000 pounds of fuel or add any.

Am willing to test this pull request on my long haul flights for QA.

**Comment by dcherrie** [comment]
**Name: dcherrie
Date of Testing: 03/03/2021
Version of the Sim: 1.13.17.0
PR Tested: #131**

**Testing Technique:** Carried out full flight using SimBrief from YSSY to NZAA. SimToolKitPro and VATSIM were used to track the flight.

**Steps you've made to test the Pull Request:**

1. Used the original fork request which does not contain the hot fix flap issue for 1.13.16.0 as the hot fix from Asobo came today.
2. Setup flight on SimBrief from YSSY to NZAA with:

**> ZFW 593.5
> FUEL 84.2
> TOW 675.7
> M 0.83
> CI 25
> FL390**

3. Took off 16R with Flaps 10 with:

**>V1 at 124kt
>VR at 138kt
>V2 at 159kt**

4. Climbed ok until FL240 then could not maintain IAS and continually dropped to almost 200kt. Climbed using VS at around 2400ftpm initially then decreased to 1800ftpm then struggled to climb at 800ftpm above FL240. Set thrust limit to CLB, disconnected autothrottle and pushed full throttles fully forward however would not increase of maintain speed during climb. Once reaching FL390, it took 6 minutes to accelerate from Mach 0.60 to 0.83.

5. Recorded each way point of AFOB.

6. Descent as seen in the VATSIM was steep at first 3300ftpm until 10,000ft. For the first part of the descent that steep the predicted fuel burn and actual fuel burn were exactly the same however when pulling up and levelling off at 10,000 a little early, I probably chewed up more fuel then moving to 1000ftpm. If done again, probably would have done a less steeper descent to make the minimums for the STAR.

7. Landed after 3 hours exactly with 36,800 lbs on board which was 800 pounds above the estimated by SimBrief.

**Overall Rating:** Much more realistic fuel burn however climb is concerning. Although being light compared to a long haul flight, I'd worry if the planes performance could cause stalls for heavy takeoffs.

**Conclusion**
Looking at the recorded data, these were the main data points.

> Total flight used 98.34% of the planned total fuel.
> Climb used only 65.75% of the planned climb fuel.
> Cruise used 3.75% more cruise fuel than planned.
> Descent used 5.5 times more descent fuel than planned.

Under performing in a slow climb offset the fuel used in descent. I'd suggest that the descent fuel not be focussed on as too much energy was spent in the first part of the descent.

**Links**
[747-8 Fuel Consumption Test - Data Summary](https://github.com/saltysimulations/salty-747/files/6074351/747-8.Fuel.Consumption.Test.pdf)
[VATSIM Speed and Vertical Profile](https://map.vatsim.net/?uid=76682a572fca2c0d8273277f121cd559)
[SimBrief Documentation with AFOB](https://github.com/saltysimulations/salty-747/files/6074353/YSSYNZAA_PDF_03Mar21.pdf)

**Comment by DesertRick13** [comment]
Thanks, all, for your for your work on the fuel flow issue. I remember when we started testing, and I ran out of fuel on a flight from Everett to Miami. Now the issue is the opposite. I know there is work being done on fuel flow scalar and other elements. Because this seems to be at a wall of either having realistic fuel management or thrust, but not both, I have a very simplistic question: What are **_all_** the elements that changed from the early engine model to the one we are flying on salty V2.1?  I half jokingly want to take all the changes and divide them in two and voila! I ask this question, not in the spirit of a useless voice from the peanut gallery, but maybe as someone who will cause a pause in thought that could lead to a different direction in problem solving. Something my wife does with me when I am at an impasse,  that causes me to grumble until the lightbulb turns on. Anyway, thanks for your hard work.

**Comment by dcherrie** [comment]
> Thanks, all, for your for your work on the fuel flow issue. I remember when we started testing, and I ran out of fuel on a flight from Everett to Miami. Now the issue is the opposite. I know there is work being done on fuel flow scalar and other elements. Because this seems to be at a wall of either having realistic fuel management or thrust, but not both, I have a very simplistic question: What are **_all_** the elements that changed from the early engine model to the one we are flying on salty V2.1? I half jokingly want to take all the changes and divide them in two and voila! I ask this question, not in the spirit of a useless voice from the peanut gallery, but maybe as someone who will cause a pause in thought that could lead to a different direction in problem solving. Something my wife does with me when I am at an impasse, that causes me to grumble until the lightbulb turns on. Anyway, thanks for your hard work.

I have no idea regarding the real thrust of the aircraft so currently I am just trying to find a suitable fuel flow scalar value to use. In the original issue I have a recent post regarding data from fuel consumption during flights and worked out for it to be somewhere between 35-45% less than what it should be so am currently testing a suitable value.

I tested a flight from Singapore to London with a fuel flow scalar value of 1.12 and used SimBrief auto-calculate the Cost Index and that flight actually went very well with being under 10,000 lbs difference on landing. During the flight however I flew at maximum speed rather than ECON.

Am currently completing a London to Singapore with a fuel flow scalar value of 1.16 and used M88 as the cruise profile however am 70,000 pounds under what I should have consumed by this far. Am wondering if the hot fix for the flaps changed anything to do with cruise drag.

Anyway, my short term goal is to just fine a fuel flow consumption that is more realistic so you don't land with 1-2/3rds of the plane still filled with fuel.

[Original Issue Report](https://github.com/saltysimulations/salty-747/issues/106#issuecomment-788690079)

**Comment by 747-4EVER** [comment]
The problem is that the thrust and fuel burn scalars both affect the total fuel burn, and trying to attain the best balance between realistic climb performance, fuel flow and N1 is difficult as a result.
However if I think the priorities for accuracy when compromise is needed should be as follows:
1. Climb Performance
2. Fuel Flow
3. N1 

One of the problems with testing is max climb thrust does not work properly in the sim, and this is what the target numbers are based on.

**Comment by DesertRick13** [comment]
Has anyone noticed an engine performance difference  between 1.12.13 and 1.13.16 or 17? The fuel consumption is still off, but it seems to me that the engines have a little less thrust. I notice this in getting the plane to begin taxiing, the takeoff roll, and in flight. I've only flown a couple times since the update, and always with Salty v2.1, but it seems to feel a little different. I almost always am near MTOW at takeoff, so that is consistent.

**Comment by dcherrie** [comment]
> Has anyone noticed an engine performance difference between 1.12.13 and 1.13.16 or 17? The fuel consumption is still off, but it seems to me that the engines have a little less thrust. I notice this in getting the plane to begin taxiing, the takeoff roll, and in flight. I've only flown a couple times since the update, and always with Salty v2.1, but it seems to feel a little different. I almost always am near MTOW at takeoff, so that is consistent.

I think there may have been some tinkering between updates by Asobo but nothing substantial. I'm currently testing another long haul flight after last night and am getting the indication to fix the fuel consumption issue to be more realistic but not addressing the thrust issue is that the fuel flow scalar should be around 1.16 to 1.334 instead of 0.8.

Before the update and using a the default fuel flow scalar of 0.8. My flights were about 40-45% off of what SimBrief was saying so I adjusted the fuel flow scalar to 1.12 and was a bit off still so am currently testing at 1.16 and I'm reliably getting at cruise an error rate of somewhere around 15 to 25%. 

In my calculations I'm mainly addressing the cruise fuel burn. Due to the thrust and so many variables with VNAV and CI and thrust limiters, the climb and descent fuel predictions are way off by 5-10 thousand pounds of fuel.

**Comment by dcherrie** [comment]
> The problem is that the thrust and fuel burn scalars both affect the total fuel burn, and trying to attain the best balance between realistic climb performance, fuel flow and N1 is difficult as a result.
> However if I think the priorities for accuracy when compromise is needed should be as follows:
> 
> 1. Climb Performance
> 2. Fuel Flow
> 3. N1
> 
> One of the problems with testing is max climb thrust does not work properly in the sim, and this is what the target numbers are based on.

As a regular user of the 747 and I assume that a lot of others would agree is that they don't notice unrealistic climb performance or N1, they notice that they are landing with only 1/3rd of their fuel burnt and and having to remove 150,000 pounds of fuel to get under their landing weight on long haul flights.

If the autothrottle is not behaving correctly and unable to be fixed, I would suggest to concentrate on getting fuel burn more accurate as it is currently achievable rather than worrying about thrust performance which most average simmers won't notice.

**Comment by DesertRick13** [comment]
I am not so sure about thrust performance. I am not a fan of VNAV and use V/S to get to my altitudes. I would not want to compromise thrust performance to the point that the takeoff roll is overly long and the climb performance is not "in the ballpark" of the performance listed. It was such a fight with Asobo to get an autothrottle that would keep the mach number requested, I'm not sure I want to go there with the autothrottle again. I get your point about fuel dump, and it is irksome to have to dump so much at the end of a long flight. N1 is the least of my considerations, but they are all tied together. I'll try to do some tinkering this weekend san see if I can find a sweeter spot, though I fully admit there's been a lot of work done with some knowledgeable folk already.

**Comment by 747-4EVER** [comment]
The good news is actually while changing the thrust scalar will affect the fuel flow, the reverse is not the case, so these two variables can be tuned independently until satisfactory. However N1/N2 are functions of the thrust scalar so there has to be a compromise there, but it would be possible to use an algorithm to "fake" the N1 gauges to a corrected value if needed.

I'm working on other features and haven't had time to test this since the new patch came out, so I am open to suggestions of new values for the fuel and thrust scalars if they can achieve closer to the book values than current.

**Comment by DesertRick13** [comment]
Since the next Asobo update is coming out next week, I'm kinda hesitant to put too much thought  this until I see what changes there may be.

**Comment by zakiack** [comment]
Name: zakiack#8247
Date of testing: Current date 04/03/20221
Version of the sim: 1.13.17.0
PR Tested: #131 

Testing technique: Performed a flight from KSFO - PHNL
Steps you've made to test the Pull Request:
1. Loaded into aircraft cold and dark and did full startup with fmc and engines
2. Loaded aircraft according to simbrief OFP [KSFOPHNL_PDF_1614912952.pdf](https://github.com/saltysimulations/salty-747/files/6088247/KSFOPHNL_PDF_1614912952.pdf)
3. On climb out, noted time between passing every thousand feet from FL210 to FL380, and calculated avg vertical speed throughout the climb
4. Continued flight
5. Took note of landing fuel at end of flight

Overall Rating: Good
Conclusions of the testing: Not sure what proper fuel burn/engine power in the 747 is so i'll just list my observations

Done using VNAV and LNAV along the route

| Altitude (FL)  | Avg. Vertical Speed (FPM) |
| ------------- | ------------- |
| 220  | 1464  |
| 230  | 983  |
| 240* | 939 |
| 250 | 895 |
| 260 | 1153 |
| 270 | 909 |
| 280 | 857 |
| 290 | 750 |
| 300 | 645 |
| 310 | 667 |
| 320 | 870 |
| 330 | 937 |
| 340 | 723 |
| 350 | 706 |
| 360 | 706 |
| 370 | 667 |
| 380 | 578 |

(* = forgot to take the time at this altitude so I found the average between the two vertical speeds around them)

Landed with 19.7 tons of fuel. Simbrief planned for 23.4 tons (LAW-ZFW)

**Comment by dcherrie** [comment]
So after doing 5 flights with only adjusting the fuel flow scalar from the current Master, here are the results. Test 1 & 2 were done with a fuel flow scalar of **1.12** and Test 3 to 5 were done with **1.276**.

I have concluded that SimBrief performance calculations for climb are totally incorrect as flight levels for SIDS are drastically wrong. All SIDS in SimBrief were about 6-8 thousand feet too high. First way points of sids only being 5-10nm from the runway expected you to be at FL10. For this reason I'm not comparing any fuel usage of climb stage but only the cruise and total fuel consumption.

**TEST 1 - London Gatwick to Changi Singapore**
> Fuel Flow Scalar of 1.12.
> Total fuel consumption was off by 67,400lbs at an error rate of 22.86%.
> Cruise fuel consumption was off by 61,100lbs at an error rate of 22.59%.
> [FFS Test 1 - EGKK to WSSS.pdf](https://github.com/saltysimulations/salty-747/files/6089883/FFS.Test.1.-.EGKK.to.WSSS.pdf)

**TEST 2 - Changi Singapore to Sydney**
> Fuel Flow Scalar of 1.12.
> Total fuel consumption was off by 21,400bs at an error rate of 13.52%.
> Cruise fuel consumption was off by 13,600lbs at an error rate of 10.48%.
> [FFS Test 2 - WSSS to YSSY.pdf](https://github.com/saltysimulations/salty-747/files/6089884/FFS.Test.2.-.WSSS.to.YSSY.pdf)

**TEST 3 - Hong Kong to London Heathrow**
> Fuel Flow Scalar of 1.276.
> Total fuel consumption was off by 14,500bs at an error rate of 5.09%.
> Cruise fuel consumption was off by 7,800lbs at an error rate of 3.03%.
> [FFS Test 3 - VHHH to EGLL.pdf](https://github.com/saltysimulations/salty-747/files/6089885/FFS.Test.3.-.VHHH.to.EGLL.pdf)

**TEST 4 - Changi Singapore to Sydney**
> Fuel Flow Scalar of 1.276.
> Total fuel consumption was off by 500bs at an error rate of 0.32%.
> Cruise fuel consumption was off by -600lbs at an error rate of -0.47%.
> [FFS Test 4 - WSSS to YSSY.pdf](https://github.com/saltysimulations/salty-747/files/6089886/FFS.Test.4.-.WSSS.to.YSSY.pdf)

**TEST 5 - Sydney to Melbourne**
> Fuel Flow Scalar of 1.276.
> Total fuel consumption was off by 100bs at an error rate of 0.4%.
> Cruise fuel consumption was off by 1,500lbs at an error rate of -22.39%.
> [FFS Test 5 - YSSY to YMML.pdf](https://github.com/saltysimulations/salty-747/files/6089887/FFS.Test.5.-.YSSY.to.YMML.pdf)

**CONCLUSION**

1. SimBrief performance calculations for SIDs are not correct and expect a much higher rate of ascent in the early stages of climb. Fuel performance cannot be compared to this stage of flight.

2. Looking at cruise performance, the rate of fuel burn is not consistent. At the start of a long haul flight, the engines burn less fuel than predicted but at later stages of the flight, it over burns the fuel predicted. Will investigate fuel burn average via time and distance and compare.

3. Using a fuel flow scalar or 1.276 gives a much more accurate fuel performance overall especially for long haul flights than that of the current 0.8.

4. The hourly average rate of fuel burn in Test 3 to 5 is currently about 1,000 litres per hour over the average fuel burn of a real 747-8 at 11,350 litres or 3,000 US gallons per hour.

Due to being unable to create realistic thrust and N1 performance due to autothrottle issues, I would recommend that for a hotfix, a fuel scalar of 1.276, in the mean time would give a noticeable improvement to the realism to match SimBrief until a better solution is found. It may not be perfect or totally accurate but its 100 times better than the fuel consumption currently is, at least for the average Sim user.

**Comment by 747-4EVER** [comment]
@dcherrie 
Yes I have been thinking about this some more and I have come to the same conclusion that adjusting only the fuel flow scalar for now is the best course of action. Once the FMC CLB thrust scheduling has been fixed, we will have a better base with which to tune the engines and I believe the current thrust reduction also causes problems accelerating with the new flap drag model. 

Can I ask if you used nil wind to generate the SimBrief plans and clear skies in sim when you did this testing? As I believe the sim winds and Simbrief can use a different data source which may affect your results.

**Comment by dcherrie** [comment]
For all the flights I used real world weather however for each of the waypoints that were recorded, I checked the winds and they were all within 5 degrees and 5 knots as to what was predicted. I won’t be able to do another flight until Monday or next weekend. I’ll do WSSS to YSSY with no winds and clear weather as it’s an easy flight with not too many waypoints over 7 hours. Is there any other settings you think I should check?

I’ve not been using VNAV for climb or speed control. I’ve been doing VS climbs and using the speed of 200-220 knots under 2,500ft then 250 knots under 10,000 then set to 310 knots until the Mach speed comes down to IAS of what has been indicated.

Also does the CI affect anything currently in the add-on? I’ve currently been using M86 for cruise profile so that the speed is constant in the SimBrief throughout the entire flight.

**Comment by 747-4EVER** [comment]
In that case if you are satisfied the winds were within 5kts this is going to be a negligible source of error and can be safely ignored. Given a TAS of 500kts the theoretical maximum error can only be 1% anyway and 5 degrees is well within the limits of normal forecast accuracy.

Given the data you've presented I'm happy to go with your recommendation for a 1.276 fuel scalar and I will remove the thrust reduction for now and resubmit to QA probably tomorrow.

As to the cost index it has no effect on anything. The current simplistic VNAV only flies a fixed M.82 regardless of any entry.

**Comment by DesertRick13** [comment]
I tried the1.276 figure. It takes quite a bit of adjustment to see the fuel coming out much quicker. Is anyone going to use simbrief with a percentage adjustment for greater accuracy, or is there a better way or tool out there?

**Pull request closed without merging**
