### PR TITLE
ISFD Init Sequence and correct ISFD behavior depending on the IRS

### PR DESCRIPTION
**Pull request by ninjomcs**
**Summary of changes**
* 90-second ISFD Init Sequence
* Amber ATT, SPD, ALT and HDG boxes when unavailable
* IRS correctly affects the ISFD (some information is not available when IRS is not aligned, like the heading)
* A while into the init sequence, some information becomes available, like speed and altitude.

**Screenshots**
ISFD just after powering on
isfd1

ISFD after about 15 seconds into init
isfd2

ISFD after init is done, while IRS is off or aligning
isfd3

ISFD after init is done and IRS is fully aligned (normal state)
isfd4

### CODE REVIEW

**Comment by oscnogbal** [comment]
I don't know if you took it into account but the ISFD comes ON as soon as the battery switch is ON. No need to select standby power to AUTO or having external power.

**Comment by ninjomcs** [comment]
Currently the ISFD comes on after standby or external power goes on, as it was in the default. Thank you for the feedback, I will make sure to try to fix it soon

**Comment by neshk16** [comment]
Name: BobbyFuzzy#4615
Date of testing: 11/11/2020
Version of the sim: 1.10.11.0
PR Tested: #69 
Object of test: Correct ISFD Sequence and Behavior

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:

Cold and Dark Start Up
Flight Plan programmed in aircraft
KPDX-KSEA
Worked As Expected 



Startup: Normal

Taxi/Takeoff : Normal

Cruise: Normal

Descent/Landing : Normal

Shutdown: Normal

Issues (If Any): None, works as intended

**Comment by BobbyFuzzy** [comment]
Name: BobbyFuzzy#4615
Date of testing: 13/11/2020
Version of the sim: 1.10.11.0
PR Tested: #69 
Object of test: ISFD

Testing technique: Tested both spawn CND and on runway, conduct flight, land and shutdown
Steps you've made to test the Pull Request:

1.  Loaded FP via world map
2. Spawned CND, startup, taxi, takeoff, land, taxi and shutdown
3. Monitor ISFD
3. Loaded FP via world map
4. Spawn on runway and same procedure as above


Flight notes

Startup: Normal

Taxi/Takeoff : Normal

Cruise: Normal

Descent/Landing : On CND run, LDG GEAR NOT DOWN memo did not disappear once gear extended. Reverse thrust also did not work when back on the ground (although not tested before flight). Spawning on runway and following flight did not have this issue.

Shutdown: Normal

Issues (If Any): As above, no issues with ISFD
Overall Rating: Good, but other side effects occurred that I've never seen before
Conclusions of the testing: Needs further testing

**Comment by ninjomcs** [comment]
I have doubts that these issues are related to the PR. Could anyone test if they’re having the same issues as described above?

**Comment by BobbyFuzzy** [comment]
I retested the same flight and couldn't reproduce.

**Pull request merged**
