### PR TITLE
Reducing Drag Coefficient for Leading Edge Slats

### PR DESCRIPTION
**Pull request by dcherrie**
Drag coefficient was being increased on the leading edge slats after full deployment at Flaps 1. 

Aircraft no longer stops increasing speed when Flaps 5 and below are deployed and can now get above 200 knots and climb.

Fine adjustments are still needed.

### CODE REVIEW

**Comment by dcherrie** [comment]
@boufogre with regards to drag coefficients, this doesn't affect lift? The only effect drag should have is increasing/decreasing the amount of thrust needed to maintain a speed right?

Cause I might go through and trial different flap settings for leading and trailing so I can at least get up to 5 to 10 knots lower than the overspeed setting whilst climbing.

**Comment by boufogre** [comment]
The thing is that engine thrust is also way higher than it should be. So until the engines are fixed, it doesn't make so much sense to fine tune the drag.

**Comment by dcherrie** [comment]
@boufogre We were looking at engine thrust before regarding fuel consumption but there are issues on Asobos end that we can't get around so we decided on stop gap measures to get a more realistic performance but not perfect.

I've removed the duplicate leading edge settings and reduced the training edge flaps for Flaps 5 - 20 by 5%. I can now climb at 3000fpm at 15 knots below the overspeed setting for each setting. Will test it out a bit more and see how it goes. Feel free to use and test it and let me know how it goes.

**Comment by boufogre** [comment]
@dcherrie I've just tried your modification. It was still showing the same lift and drag all the way from flaps 1 to flaps 30 and back.

So basically, even with your modifications, flaps 1 = flaps 30.

You can see it using the Sim Tuning window in the DevMode.

I'm putting screenshots here:

FLAPS UP

image

FLAPS 1

image

FLAPS 5

image

FLAPS 30

image

**Comment by dcherrie** [comment]
I've realised now removing the 2-6 positions from the leading edges ends up breaking the drag from Flaps 5 to 30 applying the same amount as Flaps 1.

Am trying a few other things but I think there is something to do with the scale being off. If Flaps 5 is applying full amount of drag which is 0.2, so I'm trying to readjust the entire scale between 0 and 0.2 and seeing if that works.

**Comment by bluecew** [comment]
Hey guys, I really love this mod and I used to fly the plane with it almost daily. I stopped flying the plane now because of this bug, it's a pretty significant bug that turned me away from using the mod. First, I thought this would be fixed with the stable release 0.3 but it still hasn't, is there any progress on this? I don't want a huge speed boost after flap 5, it feels odd and unrealistic. I really hope this is fixed soon, even a temporary solution is fine. Thanks for this amazing improvement mod for the 747-8!

**Comment by DesertRick13** [comment]
See the discussion in #159. There is a temporary fix, but a tradeoff. I am not sure any more work on this has been done.

**Comment by 747-4EVER** [comment]
Due to this being fixed by Asobo in Sim Update 4, this PR will be closed.

Thanks.

**Pull request closed without merging**
