### PR TITLE
chore: hard-fork

### PR DESCRIPTION
**Pull request by ninjomcs**
* renames/changes the path of all files so that they no longer overwrite any default files
* a seperate salty 747-8 is now selectable, and it is independent of the default 748

**instructions for testing:**
1. perform normal flights in both the house and salty liveries
2. try loading into the default 748 to see if it works fine

note: liveries made for the default 748 no longer work by default. to patch individual liveries, find their `aircraft.cfg` file and replace the `base_container` value to `..\Salty_B747_8i`. do the same for the fallback texture folder in the `texture.cfg` as well as the interior field in the `model.cfg`.

### CODE REVIEW

**Comment by DesertRick13** [comment]
Will you include the David Cherrie "Salty" livery as the default for the Salty version?

**Comment by DesertRick13** [comment]
A very fitting touch! BTW, really appreciate  the "Pause at TOD" tool. I needed it a couple times this past weekend.

**Comment by ninjomcs** [comment]
> Salty livery a very fitting touch! I saw about modifying liveries slightly to make them useable once this change happens. Will it be possible to have two copies of a livery, one for the default and one copied, renamed and modified for the Salty? I tried something like that in FSX and had some trouble I couldn't figure out. BTW, really appreciate the "Pause at TOD" tool. I needed it a couple times this past weekend.

yes, there shouldn't be any issues with that

**Comment by masterrob94** [comment]
image
Shouldn't be the a white triangle?

**Comment by masterrob94** [comment]
image
Stab display should disappear, if not on ground right?

**Comment by ninjomcs** [comment]
> image Stab display should disappear, if not on ground right?

it behaves the same way as in master. from what i have seen in irl sources, it currently behaves correctly: the green rectangle disappears when not on the ground, but the whole thing does not

**Comment by masterrob94** [comment]
> > image Stab display should disappear, if not on ground right?
> 
> it behaves the same way as in master. from what i have seen in irl sources, it currently behaves correctly: the green rectangle disappears when not on the ground, but the whole thing does not

Alright :-)

**Comment by mok316** [comment]
salty3
I noticed that the ECON SPD is no longer displayed on the ACT ECON CRZ page

**Pull request merged**
