### PR TITLE
LOD Draw Distance Liveries Fix

### PR DESCRIPTION
**Pull request by dcherrie**
Have increased the draw distance on the external model so liveries are no longer distorted and parts of the landing gear no longer show up when zooming out in external view and in the drone camera. 

This fixes the common issue of liveries become distorted and removing sections when swapping from LOD0 to LOD1.

### CODE REVIEW

**Comment by 747-4EVER** [comment]
Do you have a before and after pic that will show the effect of this PR?

Thanks

**Comment by dcherrie** [comment]
@747-4EVER here you go. Basically liveries are made for LOD0 which is the largest gtlf file are distroted because of the default limits being set to 150% for LOD0. When zooming out, the model switches to LOD1 which the UV map has significant chunks missing out of it due to the livery texture map being made for a model which has had faces removed to make the model size smaller.

If you are using VATSIM, you'll usually see this a lot with custom liveries on other aircraft when they are further away or when you zoom out far from your own aircraft like with the image below.

LOD Fix

**Comment by hochwang** [comment]
Well done THANK YOU; sutch a simple fix for this issue and Asobo still not able to implement this ??
What a shame - same with that reverse text Issue since beginning, unbelievable !!

regards

**Comment by dcherrie** [comment]
> Well done THANK YOU; sutch a simple fix for this issue and Asobo still not able to implement this ??
> What a shame - same with that reverse text Issue since beginning, unbelievable !!
> 
> regards

Unfortunately because of the Boeing livery, instead of doing the mapping for both sides, they were lazy and mirrored the UV and only put in LOD texture areas where it was needed for the Boeing livery. Very annoying I know and wish I could fix it but would involve creating a totally new aircraft model as the underbelly can't be imported properly into any 3D programs I use.

**Comment by hochwang** [comment]
Does this mean we never get this issue fixed ??
Think ( but not realy shure ) Flybywire wrote something about that so they will bring out
some kind off tool or a converter i realy don`t remeber exaktly but read about that.
How is on yours people side ( your salty team )
There is a member of your team ( seen some pics in the Flightsimulatorforum ) and he shows those pics with no reverse text ,OK he wrote some to that so it seems not easy with a lot off work, but would be great you guys could find a way for this stupid Issue.

Asobo really didn't solve that professionally and that is realy a shame for a Studio like that; SORRY, but i have to say that, kills realy my brain seeing sutch a nice plane done
and killing it with such a stupid issue !!

regards

**Comment by dcherrie** [comment]
> Does this mean we never get this issue fixed ??
> Think ( but not realy shure ) Flybywire wrote something about that so they will bring out
> some kind off tool or a converter i realy don`t remeber exaktly but read about that.
> How is on yours people side ( your salty team )
> There is a member of your team ( seen some pics in the Flightsimulatorforum ) and he shows those pics with no reverse text ,OK he wrote some to that so it seems not easy with a lot off work, but would be great you guys could find a way for this stupid Issue.
> 
> Asobo really didn't solve that professionally and that is realy a shame for a Studio like that; SORRY, but i have to say that, kills realy my brain seeing sutch a nice plane done
> and killing it with such a stupid issue !!
> 
> regards

I'm aware of liveries that aren't mirrored because they make use of the LOD texture areas to put a logo, where the forward cargo bay door is but I'm unaware of any program that can properly open the model that is in the Asobo gltf files. Otherwise someone would have fixed it already.

**Review by 747-4EVER — COMMENTED** [review]
Is this the vanilla Asobo 747_8I.xml that was added in the first commit?

**Comment by hochwang** [comment]
I think so - just click on the update  **747_8I.xml  7f342fe**  there you see the root Dir .

regards

**Review by 747-4EVER — APPROVED** [review]

**Pull request merged**
