### PR TITLE
feat(model): adjustments to engine start animation

### PR DESCRIPTION
**Pull request by B1rby**
During the startup of the salty 747, the engine starts instantly, the rotation of the fan blades of the 747 is extremely fast. While the GEnx startup does not have this behavior in real life. Thanks to the templates of the FBW team the animation should be more realistic. 
image

### CODE REVIEW

**Comment by Timberolic** [comment]
Name: Timbo #2992
Date of testing: Current date 13/06/2022
Version of the sim: Latest version (always forgetting, I think 1.25.9.0?) 
PR Tested: #443 

Steps you've made to test the Pull Request:
1. Select Salty 747 in Aircraft Selection
2. Spawn at KLAS at any gate
3. Turn BATTERY ON, EXT PWR ON and APU ON
4. All Fuel Pumps and Bleeds ON
5. Pull Starters and observe engine fan blade rotation

Overall Rating: Failed
Conclusions of the testing: Engines still spin at the same rate. File contents were cross checked to confirm I had the correct PR and unfortunately, blades still spin incredibly fast after Starter is pulled

**Comment by boufogre** [comment]
Idle is about just under 600 RPM.

**Comment by DesertRick13** [comment]
I have not tested the animation, only observed that from the pull of the starter handle to stable idle is just about 1 minute.

**Comment by B1rby** [comment]
Unfortunately we can't make this animation standalone so all the liveries will need to be update since the files changed are used in those liveries.

**Comment by TJCAviation** [comment]
> Unfortunately we can't make this animation standalone so yeah, all the liveries will need to be update since the files changed are used in those liveries.

to be expectected...It's an easy fix, just a pain for livery creators..

**Review by ninjomcs — APPROVED** [review]

**Pull request merged**
