### PR TITLE
Electronic Checklist

### PR DESCRIPTION
**Pull request by 747-4EVER**
**Electronic Checklist (ECL)**
--------------------------------------------------------------------------------------------------------------------------
Checklists implemented:

- [Preflight]
- [Before Start] 
- [Before Taxi] 
- [Before Takeoff] 
- [After Takeoff] 
- [Descent] 
- [Approach] 
- [Landing] 
- [Shutdown] 
- [Secure] 

**Using the ECL**
--------------------------------------------------------------------------------------------------------------------------
Checklists are appropriately initiated depending on phase of flight (spawning cold and dark vs on runway etc).

**Interaction with the ECL is currently through the FMC Menu page (Menu --> Salty) until the cursor control in the 747 model can be enabled.**

Open Loop and Closed Loop (automatically sensed) items implemented. Some values are dependant on user input (e.g. Takeoff and Landing Flaps setting must be selected in FMC to display properly on checklist).

Once a Checklist is complete, pushing the "CHKL" button on the Display Select Panel will sequence the next checklist.

After the Secure Checklist has been completed at destination, pushing "CHKL" will reset all checklists and individual checklist items, allowing a new flight to be started beginning with the Preflight Checklist again.

**Notes**
--------------------------------------------------------------------------------------------------------------------------
The checklist menus, item/checklist override and reset features are not currently implemented.

Non normal checklists are not currently implemented.

image

### CODE REVIEW

**Comment by DesertRick13** [comment]
So cool, really looking forward to trying it out! Thanks for your work!

**Comment by 747-4EVER** [comment]
Any assistance on how to enable model behaviours would be much appreciated for the cursor control.
The SDK documentation is not very helpful...
_

> Note: There is a new way to define model behaviors, used by most of the SimObjects shipped with Microsoft Flight Simulator, which is still undocumented.

_ 

The following nodes do exist in the model, don't know how usable they are:

			<UseTemplate Name="ASOBO_GT_Interaction_Tooltip">
				<NODE_ID>btn_cursor_control_sel_pilot</NODE_ID>
			</UseTemplate>
			<UseTemplate Name="ASOBO_GT_Interaction_Tooltip">
				<NODE_ID>knob_cursor_control_pilot</NODE_ID>
			</UseTemplate>
			<UseTemplate Name="ASOBO_GT_Interaction_Tooltip">
				<NODE_ID>btn_cursor_control_sel_copilot</NODE_ID>
			</UseTemplate>
			<UseTemplate Name="ASOBO_GT_Interaction_Tooltip">
				<NODE_ID>knob_cursor_control_copilot</NODE_ID>
			</UseTemplate>

**Comment by DesertRick13** [comment]
A couple of thoughts:

This conundrum may be moot after next Tuesday, as the next update is coming.  Could the tooltips be programmed with a right click of the mouse? Just a wild shot in the dark.

**Comment by zakiack** [comment]
Name: zakiack#8247
Date of testing: Current date 20/12/2020
Version of the sim: salty-747-ECL-New
PR Tested: #116 

Testing technique: Went through checklist to see functionality as well as comparing to https://flyuk.aero/assets/downloads/resources/checklists/UKV-PRD-B747-CHECKLIST-V1.0.pdf
Steps you've made to test the Pull Request:
1. See action on checklist
2. Check action
3. Compare to pdf 

Overall Rating: To be improved
Conclusions of the testing: User input definitely needs improving but it seems like that's being worked on.
When performing and action which is listed on the checklist and automatically goes into the checklist, the box around the check mark disappears and the ELC SELECT button does not work on the specific item. 

https://user-images.githubusercontent.com/76414253/102745991-27bb7100-4312-11eb-8ebc-27704a715690.mp4

**Comment by DesertRick13** [comment]
I suggest looking at the engine startup sequence. I am not sure if this really matters or not, but for some reason, I have seen 4-1-3-2 most often in the checklists.

**Comment by airifr** [comment]
> I suggest looking at the engine startup sequence. I am not sure if this really matters or not, but for some reason, I have seen 4-1-3-2 most often in the checklists.

For some reason you have seen?.. what reason then?

4 1 2 3, but with the autostart you can start 2 engines at a time, ie 4-3 1-2, 4-1 2-3, you may need turn all packs off, or only 2 off if conditions permit.

**Comment by DesertRick13** [comment]
I have no explanation, as I was clear in my entry, as to the engine startup. I am simply stating an observation, in contrast to the British simulation document that had number 1 as the initial engine for a start. Made no-comment about autostart, don't care. I defer the real life practice and technicalities to those who work with the real birds for a living as much as possible.

**Comment by airifr** [comment]
> I have no explanation, as I was clear in my entry, as to the engine startup. I am simply stating an observation, in contrast to the British simulation document that had number 1 as the initial engine for a start. Made no-comment about autostart, don't care. I defer the real life practice and technicalities to those who work with the real birds for a living as much as possible.

Great stuff..

**Pull request closed without merging**
