### PR TITLE
Removed airport display from ND when not selected

### PR DESCRIPTION
**Pull request by chloe1192**
Bing map airport is not displayed when the ARPT function is off.

Reference: FCOM 10.40.3
Screen Shot 2021-03-06 at 23 01 34-fullpage

Screenshot (332)
Screenshot (333)

### CODE REVIEW

**Comment by ninjomcs** [comment]
any references for this? @747-4EVER @oscnogbal maybe you guys know if this is accurate to RL?

**Comment by chloe1192** [comment]
> 
> 
> any references for this? @747-4EVER @oscnogbal maybe you guys know if this is accurate to RL?

On FCOM 10.40.3, it's more complex than on this PR tho.

**Review by ninjomcs — APPROVED** [review]

**Comment by tariq-a** [comment]
Name: Tariq #4753
Date of testing: Current date 27/03/2021
Version of the sim: 1.14.6.0
PR Tested: #150

### Testing technique:

Setup the aircraft parked at a gate in the cold and dark state, turned on external power and instant aligned the IRS through the Salty menu, tested the map functionality using the EFIS control panel

### Overall Rating: To be improved

### Conclusions of the testing:

- The aircraft started with the map not displayed, pressing ARPT displayed the map correctly with the blue ARPT text
- Pressing ARPT again hid the ARPT text but not the map. In this state, the range knob does not zoom the map in / out either. Pressing ARPT again fixes the range knob and the map zooms correctly again
- With ARPT on and WXR on, the map is hidden. Turning off WXR makes the map visible again
- With ARPT on and TERR on, the map is still displayed
- When the range knob is increased above 5nm the map still displays

Fixing the ARPT button function would be enough but I'd also suggest keeping the map displayed when ARPT and WXR are both on. I think this is closer to what the FCOM describes for this state as you are still meant to see the runway / taxiway outlines but currently nothing is displayed in this mode. From a practicality viewpoint, you can always hide the map with the ARPT button anyway. This would also simplify the display logic code since you no longer have to check the state of WXR and TERR, it can just be based on the ARPT button state.

The other missing things would be nice to haves:
- The map doesn't turn off when the range knob is increased above 5nm
- The map still displays in all the modes (AP, VOR, PLN instead of just MAP)

**Comment by CharlieAlphaLima** [comment]
Name: CharlieAlphaLima#1446
Date of testing: Current date 10/04/2021
Version of the sim: 1.14.6.0
PR Tested: #150

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
Spawed at EGBB
Provided ground power and instant allign 
ARPT functions as expected - Turns off when WXR is activated

Taxiway identifiers are not yet active when pressing Data while ARPT is on under 2NM

Overall Rating: Does what it says on the tin
Conclusions of the testing: Works as expected

**Pull request merged**
