### PR TITLE
feat(AP) ILS improvements

### PR DESCRIPTION
**Pull request by 747-4EVER**
### The following features have been added:

It is now possible to fly a raw data ILS i.e no need to select an approach in the FMC, only tuning the NAV RAD is required.

The AP now uses the MSFS internal ILS tracking logic which is much more accurate than the current WT port and is much less likely to lose the GS and LOC at low altitudes.

The SPD button functionality on the MCP has been implemented.

### Bug Fixes:

Once established on an ILS approach, it is no longer possible to select different AFDS modes, except for TO/GA.

Fixes a bug which prevented arming the LOC when in HDG HOLD mode.

Fixed a bug where correct Autothrottle mode would not enable upon GS capture.

When pushing TO/GA at very low level (<25 feet) , the Autothrottle no longer tries to IDLE in anticipation of landing.

TO/GA can now be initiated with Autothrottle off using H:Event H:B747_8_FMC_1_THROTTLE_TO_GA. (When AT is off, the MSFS TOGA Keybind will not work, this is a known bug which will be addressed in future)

Fixes a bug preventing selection of HDG SEL when in HDG HOLD.

### Instructions for testing:
Complete an approach without any route or approach in the FMC using manually tuned frequency. Try to intercept in HDG HOLD mode to check it is working.

Try and select different modes (FLCH, HDG SEL etc) once established on the glideslope, they should be inhibited.

Perform a go around during the approach to check correct behaviour (CTRL+SHIFT+G).

Reposition sim, set destination airport in FMC RTE page and perform an ILS by selecting the approach this time. Go-around again.

Reposition sim, select a non ILS approach (RNAV, LOC, VOR etc) and check functionality is normal.

### CODE REVIEW

**Comment by Timberolic** [comment]
Name: Timbo #2992
Date of testing: 16/03/2022
Version of the sim: 1.23.12.0
PR Tested: #403 

Testing technique: Followed instructions of the PR above
Steps you've made to test the Pull Request
The following five scenarios were tested with the following pass/fail and brief overview of actions done.
1.) PASS, aircraft captured LOC and G/S by only inputting ILS Freq in NAVRAD Page and NO FMC route inputs.
2.) PASS, aircraft flight mode would not change when fully established on ILS.
3.) PASS, PFD read SPD / TOGA / TOGA upon pressing hardware binding thru MSFS control settings and aircraft climbed to MCP altitude.
4.) PASS, aircraft autotuned ILS Frequency, fully established itself to ILS and successfully engaged TOGA with results like #3.
5.) PASS, FAC and G/P were established and TOGA was successfully engaged with results like #3 and #4.

Overall Rating: Good
Conclusions of the testing: Perhaps a small notice to ensure CLB transition is not achieved and/or to use flight modes that would knock out the risk of the aircraft still being in a CLB transition on approach. Few occasions where aircraft would go TOGA power but continued following the profile of ILS/RNAV approach. This was produced by using V/S after takeoff.

**Comment by 747-4EVER** [comment]
> Perhaps a small notice to ensure CLB transition is not achieved and/or to use flight modes that would knock out the risk of the aircraft still being in a CLB transition on approach. Few occasions where aircraft would go TOGA power but continued following the profile of ILS/RNAV approach. This was produced by using V/S after takeoff.

Can you clarify this further re. CLB transition not achieved and using V/S after takeoff?

**Comment by masterrob94** [comment]
> 

What I can say is, when I took off with TOGA button or manual thrust and LNAV VNAM armed before takeoff, the thrust won't set back to CLB after passing thrust reduction altitude. But if you engage VNAV after takeoff it works fine

**Comment by 747-4EVER** [comment]
> > 
> 
> What I can say is, when I took off with TOGA button or manual thrust and LNAV VNAV are armed before takeoff, the thrust won't set back to CLB after passing thrust reduction altitude. But if you engage VNAV after takeoff it works fine

I see what you are saying, however it's not related to this PR. The FMC thrust management hasn't been implemented really at all yet which is the source of the problems you encountered.

**Pull request merged**
