### PR TITLE
Aircraft states at loading

### LINKED ISSUE #86: Normal cockpit configuration
One thing that called my attention was how is the cockpit configured in cold and dark. There are some things that are not right.

-Hydraulic demand pumps should be OFF (not yet simulated)

-Fuel crossfeed valves 1 and 4 should be close. This valves are closed during flight after you switch OFF the override pumps from main tanks 2 and 3, so when you arrive to the aircraft they are always closed and is the duty of the next crew to reopen them for the next flight.

-Engine anti-ice switches are always set to AUTO so thats how you find them instead of OFF (At least at my company is like this)

-Window heat switches should be ON as they remain ON during the complete flight and they are not usually switched OFF

-Temperature selectors for the air conditioning should be somewhere around the middle (pointing to the AUTO) and not to the maximum cold that they are set

-PACK pushbuttons should be OFF as the crew switches them always OFF before leaving the aircraft (not simulated)

-APU bleed pushbutton should be in the OFF position as you usually switch off the bleed before switching off the APU.

### PR DESCRIPTION
**Pull request by chloe1192**
Partially fixes #86 

Window Heat is set to ON at all flight phases.
The Air Conditioning Knobs are at AUTO position.
The APU BLEED is OFF on apron start.

### CODE REVIEW

**Comment by ninjomcs** [comment]
Shouldn't APU bleed be off in every state?

**Comment by 747-4EVER** [comment]
I think this may be operator specific SOP. At my carrier it always stays on, we don't touch it unless de-icing or a non-normal checklist calls for it.

**Comment by airifr** [comment]
> Shouldn't APU bleed be off in every state?

APU bleed switch should be OFF, when APU is NOT running. After APU is stated, pilot needs wait past one minute before switching APU bleed. If ONLY AC power is needed from APU, APU bleed is not needed then switch stays OFF.
If air is needed from APU (engine start, packs..) switch comes ON.
If air not needed anymore from APU, APU bleed switch comes OFF, then only AC power from APU, then if AC power not needed from APU or APU not needed anymore, shut down APU by rotating APU switch to OFF, can OFF right after APU bleed switch OFF, as there is a cool down period before the APU actually shutdown after APU switch rotated to OFF, so don't wait need a minute like after starting, can OFF right away, as APU continues to run for a minute or so..

**Comment by ninjomcs** [comment]
> > Shouldn't APU bleed be off in every state?
> 
> APU bleed switch should be OFF, when APU is NOT running. After APU is stated, pilot needs wait past one minute before switching APU bleed. If ONLY AC power is needed from APU, APU bleed is not needed then switch stays OFF.
> If air is needed from APU (engine start, packs..) switch comes ON.
> If air not needed anymore from APU, APU bleed switch comes OFF, then only AC power from APU, then if AC power not needed from APU or APU not needed anymore, shut down APU by rotating APU switch to OFF, can OFF right after APU bleed switch OFF, as there is a cool down period before the APU actually shutdown after APU switch rotated to OFF, so don't wait need a minute like after starting, can OFF right away, as APU continues to run for a minute or so..

Yep, I am aware of when the APU bleed should be on, but what about which aircraft loading states it should be on/off at? As @747-4EVER said, I think this is specific to different carriers, so I am not sure what would be more accurate, having it on at all loading states or not, having it off only on apron start or having it off when loading from any state.

**Comment by airifr** [comment]
> > > Shouldn't APU bleed be off in every state?
> > 
> > 
> > APU bleed switch should be OFF, when APU is NOT running. After APU is stated, pilot needs wait past one minute before switching APU bleed. If ONLY AC power is needed from APU, APU bleed is not needed then switch stays OFF.
> > If air is needed from APU (engine start, packs..) switch comes ON.
> > If air not needed anymore from APU, APU bleed switch comes OFF, then only AC power from APU, then if AC power not needed from APU or APU not needed anymore, shut down APU by rotating APU switch to OFF, can OFF right after APU bleed switch OFF, as there is a cool down period before the APU actually shutdown after APU switch rotated to OFF, so don't wait need a minute like after starting, can OFF right away, as APU continues to run for a minute or so..
> 
> Yep, I am aware of when the APU bleed should be on, but what about which aircraft loading states it should be on/off at? As @747-4EVER said, I think this is specific to different carriers, so I am not sure what would be more accurate, having it on at all loading states or not, having it off only on apron start or having it off when loading from any state.

OFF

**Comment by airifr** [comment]
> > > Shouldn't APU bleed be off in every state?
> > 
> > 
> > APU bleed switch should be OFF, when APU is NOT running. After APU is stated, pilot needs wait past one minute before switching APU bleed. If ONLY AC power is needed from APU, APU bleed is not needed then switch stays OFF.
> > If air is needed from APU (engine start, packs..) switch comes ON.
> > If air not needed anymore from APU, APU bleed switch comes OFF, then only AC power from APU, then if AC power not needed from APU or APU not needed anymore, shut down APU by rotating APU switch to OFF, can OFF right after APU bleed switch OFF, as there is a cool down period before the APU actually shutdown after APU switch rotated to OFF, so don't wait need a minute like after starting, can OFF right away, as APU continues to run for a minute or so..
> 
> Yep, I am aware of when the APU bleed should be on, but what about which aircraft loading states it should be on/off at? As @747-4EVER said, I think this is specific to different carriers, so I am not sure what would be more accurate, having it on at all loading states or not, having it off only on apron start or having it off when loading from any state.

If Airlines do their own modifications and implement SOPs then it's their call, but Salty should go with Boeing...OFF
If Salty wants make Airlines options etc then provide differents codes for each Airline then users can select the options they want through Salty menu etc, it's like the LBS/KG thing or TRACK or HDG up choice on the ND, etc..

**Comment by ninjomcs** [comment]
> If Airlines do their own modifications and implement SOPs then it's their call, but Salty should go with Boeing...OFF

Do you have any references for that? Or how did you acquire that knowledge?

**Comment by airifr** [comment]
> > If Airlines do their own modifications and implement SOPs then it's their call, but Salty should go with Boeing...OFF
> 
> Do you have any references for that? Or how did you acquire the knowledge that it's how Boeing does it?

Boeing AFM

**Comment by 747-4EVER** [comment]
> > > If Airlines do their own modifications and implement SOPs then it's their call, but Salty should go with Boeing...OFF
> > 
> > 
> > Do you have any references for that? Or how did you acquire the knowledge that it's how Boeing does it?
> 
> Boeing AFM

Can you post a reference, happy to accept if this is the case, however I am looking at the -8F AFM as we speak, the only reference to the APU Bleed in the whole document is:

_APU bleed air should not be used above 15,000 feet pressure altitude._

**Comment by airifr** [comment]
> > > > If Airlines do their own modifications and implement SOPs then it's their call, but Salty should go with Boeing...OFF
> > > 
> > > 
> > > Do you have any references for that? Or how did you acquire the knowledge that it's how Boeing does it?
> > 
> > 
> > Boeing AFM
> 
> Can you post a reference, happy to accept if this is the case, however I am looking at the -8F AFM as we speak, the only reference to the APU Bleed in the whole document is:
> 
> _APU bleed air should not be used above 15,000 feet pressure altitude._

Ok that was long time ago, so I will try to look for my file if still have it, please bear with me.

**Comment by airifr** [comment]
> > > > If Airlines do their own modifications and implement SOPs then it's their call, but Salty should go with Boeing...OFF
> > > 
> > > 
> > > Do you have any references for that? Or how did you acquire the knowledge that it's how Boeing does it?
> > 
> > 
> > Boeing AFM
> 
> Can you post a reference, happy to accept if this is the case, however I am looking at the -8F AFM as we speak, the only reference to the APU Bleed in the whole document is:
> 
> _APU bleed air should not be used above 15,000 feet pressure altitude._

Yes the APU Bleed can provide air for 1 pack up to 15,000ft. And APU cannot be started in the air, but can run from ground start up to 20,000ft.

For the reference, when shutting down the APU, the APU bleed air valve is closed, that implies that the APU bleed air switch is ON and APU continues running for a minute for cool down then shutdown. Nothing mentions about APU bleed switch to OFF, except for that after starting the APU during preflight procedur
apubleed
e is to turn APU bleed switch ON and VALVE light extinguishes..meaning that APU bleed switch OFF?

**Comment by airifr** [comment]
> > > > If Airlines do their own modifications and implement SOPs then it's their call, but Salty should go with Boeing...OFF
> > > 
> > > 
> > > Do you have any references for that? Or how did you acquire the knowledge that it's how Boeing does it?
> > 
> > 
> > Boeing AFM
> 
> Can you post a reference, happy to accept if this is the case, however I am looking at the -8F AFM as we speak, the only reference to the APU Bleed in the whole document is:
> 
> _APU bleed air should not be used above 15,000 feet pressure altitude._

Yes the APU Bleed can provide air for 1 pack up to 15,000ft. And APU cannot be started in the air, but can run from ground start up to 20,000ft.

For the reference, when shutting down the APU, the APU bleed air valve is closed, that implies that the APU bleed air switch is ON and APU continues running for a minute for cool down then shutdown. Nothing mentions about APU bleed switch to OFF, except for that after starting the APU during preflight procedure is to check APU bleed switch ON and VALVE light extinguishes..

apubleed

**Comment by 747-4EVER** [comment]
That's from the normal Amplified Procedures section of FCOM, right? 
In that case it is to verify that it is ON and turn it ON if not. It does not imply that the switch should be OFF before hand. 

That same section also lists items such as:

**APU fire switch ..........................................................................In**

Does not imply that the APU fire switch should be pulled before you arrive at the aircraft of course.

I can't find any explicit instruction to turn off APU Bleed in either -400 or -8 FCOMs I have, so the natural default state should always be ON as far as I can tell.

**Comment by airifr** [comment]
> That's from the normal Amplified Procedures section of FCOM, right?
> In that case it is to verify that it is ON and turn it ON if not. It does not imply that the switch should be OFF before hand.
> 
> That same section also lists items such as:
> 
> **APU fire switch ..........................................................................In**
> 
> Does not imply that the APU fire switch should be pulled before you arrive at the aircraft of course.
> 
> I can't find any explicit instruction to turn off APU Bleed in either -400 or -8 FCOMs I have, so the natural default state should always be ON as far as I can tell.

I know, I was just stating as a check I didn't say that that meant the switch was OFF before hand...

Leave it ON if that pleases you..makes no difference

**Comment by oscnogbal** [comment]
In my company the APU bleed is OFF. I think it makes sense that way, but if that is company option I have no idea. If I had to develop a simulator aircraft I would leave it OFF.

**Comment by airifr** [comment]
> In my company the APU bleed is OFF. I think it makes sense that way, but if that is company option I have no idea. If I had to develop a simulator aircraft I would leave it OFF.

That is what I was trying to say..

**Comment by airifr** [comment]
> In my company the APU bleed is OFF. I think it makes sense that way, but if that is company option I have no idea. If I had to develop a simulator aircraft I would leave it OFF.

I would like to add, the all concept here is the make sense, why would Airlines implement this switch ON on cold n dark when they know that cold n dark means APU is OFF...well EVERYTHING is OFF lol.
We all know that some Airlines have it OFF (right) and some have it ON (improper), so knowing that Boeing never documented anything about this switch to be ON on cold n dark, I believe Salty should go with the OFF way, but only Salty can decide..

Thanks.

**Comment by ninjomcs** [comment]
So what are we thinking? We have a pilot and an engineer that disagree. Also, is it normal to have the window heat on at all times?

**Comment by oscnogbal** [comment]
In my company window heat is always ON.

**Comment by oscnogbal** [comment]
Also in real life the fact of having the bleed ON for the APU is going to translate in higher fuel consumption even if no consumer is switched ON. Usually companies dont like that.

**Comment by 747-4EVER** [comment]
I think we can agree Window Heat should always be on 👍 

Regarding APU bleed, I can only speak from experience on the -400. 

Every FCOM I have seen (My own company and ones floating around on the internet, including an ILFC one which should be as close to Boeing default as it gets, they are a leasing company not an operator) does not call for switching APU Bleed off as part of the Secure Procedure, so the crew arriving the next day to a cold aircraft would surely find the switch on.

Of course I can't deny that it may be a new procedure that I don't know to -8's that it is specifically switched OFF, but equally it could be oscnogbal's operator preference.

I have asked someone I know familiar with the -8F what his manual says. If that doesn't settle it, in the absence of anything definitive I would suggest we go with the switch OFF. After all there are only three -8i operators, so even if that is preference at only one of them then it still represents a large number of the in-service fleet.

**Comment by oscnogbal** [comment]
The day after tomorrow I will check my company’s FCOM to make sure but we always find the A/C with the switch OFF

**Comment by airifr** [comment]
Window heat always ON is the same as APU bleed always ON, the only time window heat should be ON is from about 30min before takeoff up until gate IN after landing.
Boeing is an aircraft manufacturer, the Airlines are not, they implement SOPs regarding their own philosophies most of the time disregarding Boeing or without making sense.
Most of the switches on the overhead panel , -400 or -8, should be OFF at cold n dark, but most of them are on.. Go fly the 747-100 -200 or -300 and you'll see that most switches are off position.

The glass took away the normal sense..

**Comment by oscnogbal** [comment]
Thats is not true. In my company the window heat is always ON, and apparently in the colleague’s company also. Actually when you switch it off the windows still are heated because of the backup system. So even by switching it OFF they are still heated.

**Comment by oscnogbal** [comment]
According to your logic utility switches should be off, edp switches should be off, recirculation should be off, yaw damper should be off, generators should be off, etc and all those switches are always ON

**Comment by airifr** [comment]
> Thats is not true. In my company the window heat is always ON, and apparently in the colleague’s company also. Actually when you switch it off the windows still are heated because of the backup system. So even by switching it OFF they are still heated.

Backup system is for if fail when ON, when OFF it's OFF, no electric to the windshield..

**Comment by airifr** [comment]
> According to your logic utility switches should be off, edp switches should be off, recirculation should be off, yaw damper should be off, generators should be off, etc and all those switches are always ON

Yes, everything OFF when the airplane is cold n dark. If you use the airplane why should it be OFF if you need the system? ON when needed, OFF when not..

**Comment by oscnogbal** [comment]
That is also not true. There are 4 separate switches in the maintenance panel to switch OFF the backup system. In summer some people switch the window heat OFF because it is very hot in the cockpit and they dont switch the back up system OFF.

**Comment by oscnogbal** [comment]
I am sorry but what you say is bullshit.

**Comment by airifr** [comment]
> I am sorry but what you say is bullshit.

You're right 🙂🙂🙂🙂

**Comment by DesertRick13** [comment]
I know there are some differences in how different airlines perceive "cold- dark" I think the factory cold dark, as in the first person to ever touch the controls at Everett, would be fun but very time consuming. Could there not be options to save one's particular aircraft in the state they want? Some things are pretty obvious, but on those areas where there is a genuine difference of practice, could not those settings somehow be saved? There has been so much good, complicated work done on this project, this **_seems_** like a relatively simple task.

**Comment by chloe1192** [comment]
> 
> 
> I know there are some differences in how different airlines perceive "cold- dark" I think the factory cold dark, as in the first person to ever touch the controls at Everett, would be fun but very time consuming. Could there not be options to save one's particular aircraft in the state they want? Some things are pretty obvious, but on those areas where there is a genuine difference of practice, could not those settings somehow be saved? There has been so much good, complicated work done on this project, this **_seems_** like a relatively simple task.

I have this in my plans, i just don`t know if storing too much data would affect loading times and fps.

**Comment by 747-4EVER** [comment]
Maybe an external config tool would work as an alternative that writes to the apron.flt, allowing you to customise init states, set customer options like KG/LB's etc.

**Comment by chloe1192** [comment]
I thought about an option on the CDU Options page that saves the current state.

**Comment by 747-4EVER** [comment]
I don't know if this will resolve the issue, but here is a cockpit pic of the Boeing -8I prototype on display at the Paris Airshow 2011.

You can just see that the APU is shutdown and APU bleed switch is left on.

https://flic.kr/p/dP2fjm

**Comment by airifr** [comment]
> I don't know if this will resolve the issue, but here is a cockpit pic of the Boeing -8I prototype on display at the Paris Airshow 2011.
> 
> You can just see that the APU is shutdown and APU bleed switch is left on.
> 
> https://flic.kr/p/dP2fjm

This means nothing.. it's just a pic. And you could have chosen a pic with better viewing angle? There light reflections don't help either.

**Pull request closed without merging**
