### PR TITLE
EFIS Redesign

### PR DESCRIPTION
**Pull request by 747-4EVER**
EFIS Redesign
------------------------------------------------------------------------------------
Features:

- Replaces default Asobo font on all displays (Except CDU) with custom Boeing EFIS font.

- Full overhaul of almost all EFIS elements, lines/rects etc adjusted in size, location and width to closer match real aircraft.

- ND Waypoint icons now display in Boeing style 

- ND Waypoint labels now in proper font with active label showing correctly in magenta

- Vertical Speed now displays correctly to nearest 50 feet.

image

### CODE REVIEW

**Comment by ninjomcs** [comment]
Just noticed that the waypoints are a bit oddly rotated and aligned with the line in some cases. I assume this is not intentional?

**Comment by 747-4EVER** [comment]
> Just noticed that the waypoints are a bit oddly rotated and aligned with the line in some cases. I assume this is not intentional?

For some reason SvgWaypointElement.js is rotating the waypoint 45deg if it is an Airport...

Working on a fix now.

**Comment by 747-4EVER** [comment]
Should be fixed now

**Comment by ninjomcs** [comment]
Do airports have the same icon as other waypoints in the real aircraft?

**Comment by 747-4EVER** [comment]
> Do airports have the same icon as other waypoints in the real aircraft?

In the aircraft, the departure and arrival airports are not represented as actual waypoints, instead the specific runways selected from the FMC DEP/ARR page are drawn as below, this would have to be added as a new function to MapInstrument.js.

image

**Comment by ninjomcs** [comment]
> > Do airports have the same icon as other waypoints in the real aircraft?
> 
> In the aircraft, the departure and arrival airports are not represented as actual waypoints, instead the specific runways selected from the FMC DEP/ARR page are drawn as below example of a runway 21, this would have to be added as a new function to MapInstrument.js.
> 
> image

Ah okay, but right now it is represented as a waypoint outside of this PR as well, right?

**Comment by 747-4EVER** [comment]
> > > Do airports have the same icon as other waypoints in the real aircraft?
> > 
> > 
> > In the aircraft, the departure and arrival airports are not represented as actual waypoints, instead the specific runways selected from the FMC DEP/ARR page are drawn as below example of a runway 21, this would have to be added as a new function to MapInstrument.js.
> > image
> 
> Ah okay, but right now it is represented as a waypoint outside of this PR as well, right?

I think it is drawn as a star shape, it is using a different SVG from the waypoint currently

**Comment by airifr** [comment]
> > Do airports have the same icon as other waypoints in the real aircraft?
> 
> In the aircraft, the departure and arrival airports are not represented as actual waypoints, instead the specific runways selected from the FMC DEP/ARR page are drawn as below example of a runway 21, this would have to be added as a new function to MapInstrument.js.
> 
> image

When you select a bigger scale, the airport blue circle should show, the extended runway line is only shown on lower scales ie 10 etc, if 80 is selected for example no runway extended line, likewise for the waypoints, shown under scale 40, ie 10 20, at scale 40 waypoints not shown.

**Review by ninjomcs — APPROVED** [review]

**Comment by zakiack** [comment]
Name: zakiack#8247
Date of testing: Current date 16/01/2021
Version of the sim: 1.12.13.0
PR Tested: #128 

Testing technique: Performed a flight from EDDF - EGLL 
Steps you've made to test the Pull Request:
1. Started Aircraft from cold and dark
2. Observed EICAS throughout all phases of flight
3. Compared with images and videos on Google and YouTube

Overall Rating: Good
Conclusions of the testing:

Everything was Perfect except:

The flaps selection line on the EICAS follows the flaps current position rather than going to the selected position
Screenshot_492
Not sure if this is intended, but in this video it shows the magenta flap selection line going straight to the selected position rather than following the flap bar https://youtu.be/yGAJTwSO4PM?t=311

Just a suggestion, if you're redoing the EICAS and NDs it probably wouldn't hurt to fix the NDs magenta line logic as it is quite buggy in the default
Screenshot_493

**Comment by airifr** [comment]
> The flaps selection line on the EICAS follows the flaps current position rather than going to the selected position
> Screenshot_492

This is bug, on the real aircraft, you select then on the EICAS the flap setting is updated to the set position right away then as the flap transit to position the white bar will increase or decrease respectively.
It used to show properly before last MSFS update, but MSFS decided to break this while fixing other stuff. It should be fix and other stuff remains working but for MSFS it is fix and break!...

**Comment by ninjomcs** [comment]
> Name: zakiack#8247
> Date of testing: Current date 16/01/2021
> Version of the sim: 1.12.13.0
> PR Tested: #128
> 
> Testing technique: Performed a flight from EDDF - EGLL
> Steps you've made to test the Pull Request:
> 
> 1. Started Aircraft from cold and dark
> 2. Observed EICAS throughout all phases of flight
> 3. Compared with images and videos on Google and YouTube
> 
> Overall Rating: Good
> Conclusions of the testing:
> 
> Everything was Perfect except:
> 
> The flaps selection line on the EICAS follows the flaps current position rather than going to the selected position
> Screenshot_492
> Not sure if this is intended, but in this video it shows the magenta flap selection line going straight to the selected position rather than following the flap bar https://youtu.be/yGAJTwSO4PM?t=311
> 
> Just a suggestion, if you're redoing the EICAS and NDs it probably wouldn't hurt to fix the NDs magenta line logic as it is quite buggy in the default
> Screenshot_493

Is that kind of deviation off the waypoints with the magenta line also present normally? Never seen that before

**Comment by airifr** [comment]
> > Just a suggestion, if you're redoing the EICAS and NDs it probably wouldn't hurt to fix the NDs magenta line logic as it is quite buggy in the default
> > Screenshot_493
> 
> Is that kind of deviation off the waypoints with the magenta line also present normally? Never seen that before


In the real airplane doesn't happen.
I have not seen that before either, propably on the user's aircraft, buggy.

Even using the default MSFS 747 or Salty 747, ND route line is joining all waypoints normally.

**Comment by zakiack** [comment]
> In the real airplane doesn't happen.
> I have not seen that before either, propably on the user's aircraft, buggy.
> 
> Even using the default MSFS 747 or Salty 747, ND route line is joining all waypoints normally.

It only occurs when trying to edit the route in flight. For example in the screenshot I tried to go Direct BITBU, but the magenta line connected SOBRA with my arrival airport. The aircraft still went direct BITBU and followed the waypoints afterwards properly.

**Comment by airifr** [comment]
> > In the real airplane doesn't happen.
> > I have not seen that before either, propably on the user's aircraft, buggy.
> > Even using the default MSFS 747 or Salty 747, ND route line is joining all waypoints normally.
> 
> It only occurs when trying to edit the route in flight. For example in the screenshot I tried to go Direct BITBU, but the magenta line connected SOBRA with my arrival airport. The aircraft still went direct BITBU and followed the waypoints afterwards properly.

Ok now we understand why you got this, you did something that triggered this. This is normal for the MSFS 747 lol, do not worry. The best way is to leave the RTE and LEGS pages ALONE during flight 😅, until MSFS decides to fix the WHOLE -8 FMS.

**Comment by valenzz2004** [comment]
Category: QA Tester
Name: Valenzz2004#7802
Date of testing: 17/01/2021
Version of the sim: 1.12.13.0
PR Tested: #128 
Object of test: check functionality of EFIS redesign

Testing technique: Full IFR flight 
Steps you've made to test the Pull Request:

1. loaded in C/D at LPAZ and set aircraft up for a full flight 
2. started engines and taxied to the active runway
3. departed as planned
4. completed arrival and landed as planned


Flight notes (If required): 

Issues (If Any): -once arrival was selected all enroute waypoint names dissapeared on the pfd
-not sure if related but i lost all vnav alt intervention function 
Overall Rating: Good
Conclusions of the testing: font works as planned and makes the plane look quite realistic but there are some small qwerks that my need to be edited
Screenshots( if any):

**Comment by BobbyFuzzy** [comment]
I'm yet to complete a full flight with this PR but a few small things that initially jumped out at me was 

- The active waypoint in the ND seems to have a small white outline around it.
- Font generally looks great, I think (and I might be nitpicking/wrong here) the weight looks too much in some places for example the range indication, way points and active in top right on the ND. However[ looking at some real world examples](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Navigation_Display_%28ND%29_on_Boeing_747-400_%28cropped%29.jpg/840px-Navigation_Display_%28ND%29_on_Boeing_747-400_%28cropped%29.jpg), this may be more due to the fact the letters are a bit close together, adding some positive kerning would be my first thing to change.
- If it is possible to use a version of the font that has more anti-aliasing, I would suggest that too.

**Comment by BobbyFuzzy** [comment]
Category: QA Tester
Name: BobbyFuzzy#4615
Date of testing: 20/01/2021
Version of the sim: 1.12.13.0
PR Tested: #128
Object of test: EFIS redesign

Testing technique: Conduct flight IFR 
Steps you've made to test the Pull Request:

Loaded in cold and dark, set flight plan via world map
Executed flight
Monitored all displays, switching between all available displays, zoom levels and data

Flight notes (If required): None

Issues (If Any):  Selecting DATA for the EHSI shows circles around the waypoints, this is not true to life (see below)

Also see the [other comment I left](https://github.com/saltysimulations/salty-747/pull/128#issuecomment-761826241) for other issues I found.

> I'm yet to complete a full flight with this PR but a few small things that initially jumped out at me was
> 
> * The active waypoint in the ND seems to have a small white outline around it.
> * Font generally looks great, I think (and I might be nitpicking/wrong here) the weight looks too much in some places for example the range indication, way points and active in top right on the ND. However[ looking at some real world examples](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Navigation_Display_%28ND%29_on_Boeing_747-400_%28cropped%29.jpg/840px-Navigation_Display_%28ND%29_on_Boeing_747-400_%28cropped%29.jpg), this may be more due to the fact the letters are a bit close together, adding some positive kerning would be my first thing to change.
> * If it is possible to use a version of the font that has more anti-aliasing, I would suggest that too.

As has been discussed, not only airports show as 'star waypoints' all other navaids are showing as the same symbol. Each navaid should show as a different symbol depending on what it represents (again above image shows some examples).

Overall Rating: A good start
Conclusions of the testing: Needs some work, however I feel the bulk of the work would be on improving the EHSI which may be outside of the scope of this PR. Consider - if possible - my suggested alterations to the font before merging, otherwise operationally it works fine.

Screenshots( if any):

Screenshot 2021-01-20 100355

image

**Comment by 747-4EVER** [comment]
Going to make some adjustments based on QA feedback. I will see what a slightly more spaced font looks like.

**Comment by 747-4EVER** [comment]
Changes are ready for review. Enjoy!

image

**Comment by airifr** [comment]
> Changes are ready for review. Enjoy!
> 
> image

Can you correct the EICAS trim indication also? The green band/green box are only for takeoff trim range, when liftoff they disappear and only the vertical scale left and the pointer.

**Comment by 747-4EVER** [comment]
> > Changes are ready for review. Enjoy!
> > image
> 
> Can you correct the EICAS trim indication also? The green band/green box are only for takeoff trim range, when liftoff they disappear and only the vertical scale left and the pointer.

I will do further changes in future, this will be one of them however I have to limit the scope of this PR at some point or it's never going to get to QA, I think there's enough for now.

Things on the to do list:
Highlight CMD/FD on FMA when mode changes.
Highlight altitude when approaching commanded.
Visual changes to ILS deviation scales.
Add Track line to ND.
Smaller ND heading bug.
Update waypoint, station, airport map symbology.
Autotune nearest 2 VORs, adding the bottom display and the needles.
Add FMC position source display GPS/IRS/DME.
Hide Wind Vector/Velocity display when below 3kts.
Adjust EICAS Engine bars.

**Comment by airifr** [comment]
> > > Changes are ready for review. Enjoy!
> > > image
> > 
> > 
> > Can you correct the EICAS trim indication also? The green band/green box are only for takeoff trim range, when liftoff they disappear and only the vertical scale left and the pointer.
> 
> I will do further changes in future, this will be one of them however I have to limit the scope of this PR at some point or it's never going to get to QA, I think there's enough for now.
> 
> Things on the to do list:
> Highlight CMD/FD on FMA when mode changes.
> Highlight altitude when approaching commanded.
> Visual changes to ILS deviation scales.
> Add Track line to ND.
> Smaller ND heading bug.
> Update waypoint, station, airport map symbology.
> Autotune nearest 2 VORs, adding the bottom display and the needles.
> Add FMC position source display GPS/IRS/DME.
> Hide Wind Vector/Velocity display when below 3kts.
> Adjust EICAS Engine bars.

Ok thanks, yes that is a good list already, do what's best. Thank you for improving our 747!

Add Track line to ND.
We will be able to choose TRK up or HDG up? I fly HDG up, the correct way, not sure why Boeing decided to implement track up on ND. The nose of the aircraft is pointing to a heading not a track...

**Comment by airifr** [comment]
> > > Changes are ready for review. Enjoy!
> > > image
> > 
> > 
> > Can you correct the EICAS trim indication also? The green band/green box are only for takeoff trim range, when liftoff they disappear and only the vertical scale left and the pointer.
> 
> I will do further changes in future, this will be one of them however I have to limit the scope of this PR at some point or it's never going to get to QA, I think there's enough for now.
> 
> Things on the to do list:
> Highlight CMD/FD on FMA when mode changes.
> Highlight altitude when approaching commanded.
> Visual changes to ILS deviation scales.
> Add Track line to ND.
> Smaller ND heading bug.
> Update waypoint, station, airport map symbology.
> Autotune nearest 2 VORs, adding the bottom display and the needles.
> Add FMC position source display GPS/IRS/DME.
> Hide Wind Vector/Velocity display when below 3kts.
> Adjust EICAS Engine bars.

Ok thanks, yes that is a good list already, do what's best. Thank you for improving our 747!

**Comment by 747-4EVER** [comment]
Bugs are gone, should be good for QA now.

**Comment by valenzz2004** [comment]
Category: QA Tester
Name: Valenzz2004#7802
Date of testing: 23/01/2021
Version of the sim: 1.12.13.0
PR Tested: #128 
Object of test: check functionality and quality of the new EFIS font 

Testing technique: Page checks
Steps you've made to test the Pull Request:

1. loaded in C/D
2. powered up aircraft and checked PFD and ND
3. checked centre console pages 

Flight notes (If required):

Issues (If Any):
Overall Rating: Good
Conclusions of the testing: it looks very high quality and on all centre console there were no overlaps and adds another level of Boeing emersion, and no issues with the power and brightness of the screens 
Screenshots( if any):

**Comment by BobbyFuzzy** [comment]
Category: QA Tester
Name: BobbyFuzzy#4615
Date of testing: 28/01/2021
Version of the sim: 1.12.13.0
PR Tested: #128
Object of test: Retest updated EFIS

Testing technique: Conducted a flight and monitored EFIS
Steps you've made to test the Pull Request:

Spawned on runway
Take off and monitor EFIS
Land and shutdown
Restarted after full shutdown for final check

Flight notes (If required): None - flies fine

Issues (If Any): Small things but I would personally say there should be more kerning between characters (see above reference images). I also now noticed the magenta colour using throughout seems to be too saturated. Difficult to tell if accurate or not because of differing lighting conditions on reference images vs the sim however. Further, the white line around the active waypoint on the ND is still present along with the DATA circles on the ND being offset. These are small things but the fixes may be out of the scope of this PR.

Overall Rating: Good, can be improved but only small issues
Conclusions of the testing: All working OK but some accuracy queries to be resolved if desired

**Comment by 747-4EVER** [comment]
> Category: QA Tester
> Name: BobbyFuzzy#4615
> Date of testing: 28/01/2021
> Version of the sim: 1.12.13.0
> PR Tested: #128
> Object of test: Retest updated EFIS
> 
> Testing technique: Conducted a flight and monitored EFIS
> Steps you've made to test the Pull Request:
> 
> Spawned on runway
> Take off and monitor EFIS
> Land and shutdown
> Restarted after full shutdown for final check
> 
> Flight notes (If required): None - flies fine
> 
> Issues (If Any): Small things but I would personally say there should be more kerning between characters (see above reference images). I also now noticed the magenta colour using throughout seems to be too saturated. Difficult to tell if accurate or not because of differing lighting conditions on reference images vs the sim however. Further, the white line around the active waypoint on the ND is still present along with the DATA circles on the ND being offset. These are small things but the fixes may be out of the scope of this PR.
> 
> Overall Rating: Good, can be improved but only small issues
> Conclusions of the testing: All working OK but some accuracy queries to be resolved if desired

Thanks for the feedback,

Regarding the character spacing difference, it looks like the spacing is a bit different on the older -400 CRT type display that you posted. On the newer -400 and -8s they have LCDs which have a different appearance (attached below) you can see the characters are closer and more uniformly spaced.

image

You can see the difference between the CRT and LCD spacing most clearly in this waypoint example:

image

Regarding the magenta colour, you are right it seems more pink than magenta really, it should be an easy fix.

Also I will try and find what is causing the circles, I think it is coming from something outside the EFIS files I have worked on. They don't exist on the Boeing EFIS, it should be easy to delete them if I can find them...

**Comment by 747-4EVER** [comment]
image

Have changed the magenta shade, fixed the circles bug and adjusted a few other items (details in the commits above).

Only minimal changes, a quick QA would be appreciated.

**Comment by BobbyFuzzy** [comment]
You're absolutely right my references weren't probably the best - apologies. Changes look great to me, thanks for your work.

**Comment by airifr** [comment]
> image
> 
> Have changed the magenta shade, fixed the circles bug and adjusted a few other items (details in the commits above).
> 
> Only minimal changes, a quick QA would be appreciated.

Magenta looks unrealistic now, this isn't the magenta we see in the real airplane, the magenta before was way more close to the real one..

What's up with that?

**Comment by BobbyFuzzy** [comment]
> > image
> > Have changed the magenta shade, fixed the circles bug and adjusted a few other items (details in the commits above).
> > Only minimal changes, a quick QA would be appreciated.
> 
> Magenta looks unrealistic now, this isn't the magenta we see in the real airplane, the magenta before was way more close to the real one..
> 
> What's up with that?

Have you looked at the references above? Do you have any references you can provide that make this more unrealistic than the previous implementation?

**Comment by airifr** [comment]
> > > image
> > > Have changed the magenta shade, fixed the circles bug and adjusted a few other items (details in the commits above).
> > > Only minimal changes, a quick QA would be appreciated.
> > 
> > 
> > Magenta looks unrealistic now, this isn't the magenta we see in the real airplane, the magenta before was way more close to the real one..
> > What's up with that?
> 
> Have you looked at the references above? Do you have any references you can provide that make this more unrealistic than the previous implementation?

LOL

**Comment by ninjomcs** [comment]
> > > > image
> > > > Have changed the magenta shade, fixed the circles bug and adjusted a few other items (details in the commits above).
> > > > Only minimal changes, a quick QA would be appreciated.
> > > 
> > > 
> > > Magenta looks unrealistic now, this isn't the magenta we see in the real airplane, the magenta before was way more close to the real one..
> > > What's up with that?
> > 
> > 
> > Have you looked at the references above? Do you have any references you can provide that make this more unrealistic than the previous implementation?
> 
> LOL

To me, the new color looks more accurate. If you believe it is not, please post some references as Bobby said, because in my opinion the ones posted in here resemble the new magenta more closely.

**Comment by airifr** [comment]
> > > > > image
> > > > > Have changed the magenta shade, fixed the circles bug and adjusted a few other items (details in the commits above).
> > > > > Only minimal changes, a quick QA would be appreciated.
> > > > 
> > > > 
> > > > Magenta looks unrealistic now, this isn't the magenta we see in the real airplane, the magenta before was way more close to the real one..
> > > > What's up with that?
> > > 
> > > 
> > > Have you looked at the references above? Do you have any references you can provide that make this more unrealistic than the previous implementation?
> > 
> > 
> > LOL
> 
> To me, the new color looks more accurate. If you believe it is not, please post some references as Bobby said, because in my opinion the ones posted in here resemble the new magenta more closely.

I hope I'm not making any toxic comment here....well this look undersaturated compared to the real one, looks dull...

**Comment by airifr** [comment]
I wasn't sure about that shared magenta color, I'm even less sure about that yellow (??) (amber?) caution messages..

**Comment by airifr** [comment]
I wasn't sure about that shaded magenta color, I'm even less sure about that yellow (??) (amber?) caution messages..

**Comment by ninjomcs** [comment]
you're right, just noticed the caution message color is a bit off. i'll probably fix it soon

**Comment by airifr** [comment]
That's great. Thank you for improving the MSFS -8!
This is probably off topic but just to mention the winds don't show anymore on the ND, once 100kt gs..

**Comment by ninjomcs** [comment]
wind displays fine for me

**Comment by airifr** [comment]
So I start the takeoff roll, no winds displayed (blank), as the aircraft accelerates passed 100kt gs, the winds should show on the ND, but on mine it shows dashes during the rest of the takeoff roll, then when liftoff winds show. They should show above 100kt gs not at after liftoff, up until below 100kt during landing roll.
Not sure why mine not showing anymore above 100kt, it used to show correctly but not anymore..

Look from 05:20

https://youtu.be/Z8VUXpuF0_I

**Comment by ninjomcs** [comment]
ah, i thought you meant that this changed after this pr. please open an issue https://github.com/saltysimulations/salty-747/issues

**Pull request merged**
