### PR TITLE
Ported 1.11.6 Asobo changes

### PR DESCRIPTION
**Pull request by ninjomcs**
**Summary of changes**
* Changes to fuel consumption
* A lot of flight model changes

Note to QA: Try to test the fuel consumption, is it more accurate or worse than before, when you use estimates from for example SimBrief? Watch for general changes in the flight model as well.

### CODE REVIEW

**Comment by neshk16** [comment]
Name: ExtraChromosome#2958
Date of testing: 11/27/2020
Version of the sim: 1.11.6
PR Tested: #102 
Object of test: General Changes

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:

Cold and Dark Start Up
Flight Plan programmed in aircraft
KPDX-KSEA
Worked As Expected

Startup: Normal

Taxi/Takeoff : Normal

Cruise: Normal

Descent/Landing : Normal

Shutdown: Normal

Issues (If Any): None, works as intended

**Comment by maretex** [comment]
Name: pmaretti#7885
Date of testing: 11/28/2020
Version of the sim: 1.11.6
PR Tested: #102
Object of test: Change on Flight model

Testing technique: Normal IFR flight KATL-KDFW 
Steps you've made to test the Pull Request:

Cold and Dark Start Up
Flight Plan programmed in game menu prior to flight
KATL-KDFW


Startup: Normal

Taxi/Takeoff : Normal

Cruise: AP is holding the altitude ~100ft off the Altitude set (for example, cruising at 9900 ft when the altitude set was 10000 ft)

Descent/Landing : Normal

Shutdown: Normal

Issues (If Any): Altitude hold 100ft off. Apart from that, it looks OK;
icing happening even when de-ice is set on AUTO; didn't affect the plane, so could be visual only

**Comment by ninjomcs** [comment]
Regarding the altitude hold issue, it occurs in all versions I tested: default, ee5c17b and #102.

**Comment by BobbyFuzzy** [comment]
@ninjomcs @maretex This also happens in the 787. Asobo issue for sure.

**Comment by Skynetxp** [comment]
I realized that something like the altitude issue, it happens also with speed especially on the G/S. You set 142 kts, and the plane climbs down at 146. You set 146 and it sticks at 148.

**Comment by ninjomcs** [comment]
#104

**Pull request merged**
