### PR TITLE
Ported Asobo 1.12.13 changes

### PR DESCRIPTION
**Pull request by ninjomcs**
**Summary of changes**
* Ported Asobo changes from 1.12.13

### CODE REVIEW

**Comment by zakiack** [comment]
Name: zakiack#8247
Date of testing: Current date 23/12/2020
Version of the sim: 1.12.13
PR Tested: #119

Testing technique: Was gonna do a flight from OERK - OMDB until problems arose
Steps you've made to test the Pull Request:
1. Started airplane in cold and dark but fmc wouldn't turn on
2. Re-installed aircraft, fmc still wouldn't turn on
3. Deleted all liveries, fmc still wouldn't turn on
4.
5.

Overall Rating: To be improved
Conclusions of the testing: The fmc just doesn't turn on. I am unable to go any further

**Comment by ninjomcs** [comment]
> Name: zakiack#8247
> Date of testing: Current date 23/12/2020
> Version of the sim: 1.12.13
> PR Tested: #119
> 
> Testing technique: Was gonna do a flight from OERK - OMDB until problems arose
> Steps you've made to test the Pull Request:
> 
> 1. Started airplane in cold and dark but fmc wouldn't turn on
> 2. Re-installed aircraft, fmc still wouldn't turn on
> 3. Deleted all liveries, fmc still wouldn't turn on
> 
> Overall Rating: To be improved
> Conclusions of the testing: The fmc just doesn't turn on. I am unable to go any further

Uninstalling the A32NX fixed that issue for me. There seems to be a conflict present.

**Comment by airifr** [comment]
This is because MSFS moved the FMC brightness from the center knob above primary EICAS (which was wrong to start with) to the overhead panel aisle knob, so if this knob is off, FMC won't light up (which is wrong again, not sure what MSFS was thinking when doing this), nothing to do with liveries, aircraft install etc. If FMC won't turn on it's because of that knob turned off, again in the real aircraft that knob doesn't light up the CDU, but for MSFS yes..

FlightSimulator_2020_12_23_15_58_35_515

**Comment by ninjomcs** [comment]
> This is because MSFS moved the CDU brightness from the center knob above primary EICAS (which was wrong to start with) to the overhead panel aisle knob, so if this knob is off, FMC won't light up (which is wrong again, not sure what MSFS was thinking when doing this), nothing to do with liveries, aircraft install etc. If FMC won't turn on it's because of that knob turned off, again in the real aircraft that knob doesn't light up the CDU, but for MSFS yes..
> 
> FlightSimulator_2020_12_23_15_58_35_515

While you are correct in saying that the knob controls the brightness, the issue described here is caused by the A32NX being installed. When it is, the knob doesn't do anything, and the CDU stays black.

**Comment by airifr** [comment]
>> While you are correct in saying that the knob controls the brightness, the issue described here is caused by the A32NX being installed. When it is, the knob doesn't do anything, and the CDU stays black.

I see, so that 32nx is a separate add-on? How is it installed?

**Comment by airifr** [comment]
> While you are correct in saying that the knob controls the brightness, the issue described here is caused by the A32NX being installed. When it is, the knob doesn't do anything, and the CDU stays black.

I see, so that 32nx is a separate add-on? How is it installed?

**Comment by zakiack** [comment]
Name: zakiack#8247
Date of testing: Current date 23/12/2020
Version of the sim: Version the tester uses
PR Tested: #119 

Testing technique: Performed a flight from OTHH - OMDB via NAML1E NAMLA N300 LORID LORI1E
Steps you've made to test the Pull Request:
1.  Started the aircraft from cold and dark
2.  Attempted to use features which have been added by salty simulations, as well as seeing if other features worked

Overall Rating: To be improved
Conclusions of the testing: 
Flaps Setting only shows up on fmc after inputting VSpeeds

https://user-images.githubusercontent.com/76414253/103051283-5a9c7980-454b-11eb-8224-fd7ce29015d6.mp4

Aircraft Refuses to establish on Localizer nor Glideslope on ILS approaches
      Did multiple S turns around the localizer to try to get established but the aircraft refused (ILS 12R OMDB)

**Comment by valenzz2004** [comment]
Category: QA Tester
Name: Valenzz2004#7802
Date of testing: 24/12/2020
Version of the sim: 1.12.13.0
PR Tested: #119 
Object of test: Ported Asobo 1.12.13 changes

Testing technique: Full IFR Flight 
Steps you've made to test the Pull Request:

1. Spawned C/D at EGLL
2. Filled out manual flightplan with DCT only
3. Set perf info
4. Started APU( went as planned)
5. Pushed and started engines
6. Taxied to the active runway (went as planned)
7. TO and departure with LNAV and VNAV 
8. used simbrief T/D and selected arrival
9. Completed arrival with VNAV and entered approach ILS Z 32L
10. ILS freq crosschecked with navigraph chart
11. Landed 32l and taxied to stand

Flight notes (If required): EGLL/27R GOGSI2F GOGSI DCT SAM DCT MARUK DCT LELNA DCT BASIK
DCT NOVAN DCT NONTU NONTU2C LEMD/32L

Issues (If Any):
-As in test Above flap setting only selectable after imputing v speeds
-VNAV worked well for departure however at a step climb it reduced speed to managed descent speed so speed intervention was used
-Unlike previous test i had a good LOC and G/S intercept
-Not sure if its a known issue but spoilers didn't deploy on touchdown
Overall Rating: Good
Conclusions of the testing: ready to go only minor issues that can easily be rectified by the user and can be fixed at a later date and was actually very enjoyable to fly
Screenshots( if any):

**Pull request merged**
