### PR TITLE
Port to asobo 1.14.5

### LINKED ISSUE #160: [BUG] LNAV & VNAV when engaging Autopilot after Asobo says its fixed.
**Version of the mod**
Latest Master Dev at time of post.

**Describe the bug**
LNAV and VNAV engage no matter what you have selected when engaging autopilot.

**To Reproduce**
1. Select HDG HOLD, ALT HOLD and SPD
2. Engage Autopilot
3. Watch LNAV and VNAV engage instead.

**Expected behavior**
Whatever is selected should engage once turning on autopilot. If nothing is selected I believe ALT HOLD and HDG HOLD should engage.

**Screenshots**

**References**

**Additional information**
Is this bug present in the default 747-8, or only in the mod?
Unsure, have not had time to test.

Your Discord:
davidcherrie#1672

### PR DESCRIPTION
**Pull request by r4yman**
### Changelist:

- **[flightmodel.cfg](SimObjects/Airplanes/Asobo_B747_8i/flight_model.cfg)**
  * Flap coefficients adjusted
  * Flap positions adjusted
- **[747_8I_INTERIOR.xml](SimObjects/Airplanes/Asobo_B747_8i/model/747_8I_INTERIOR.xml)**
  * MISC templates edited
- **[Boeing_FMA.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/Boeing_FMA.js)**
  * FMA uses constant for approach type instead of hardcoded value
- **[AttitudeIndicatior.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/AttitudeIndicator.js)**
  * changed `strokeWidth` from `1.5` -> `2.5`
  * function parameter order changed for
    - `calculatePosXFromBank`
    - `calculatePosYFromPitch`
- **[AlitmeterIndicator.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/AltimeterIndicator.js)**
  * added check that does not affect the B747
- **[HSIndicator.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/HSIndicator.js)**
  * added empty value check for `localizer`
- **[ILSIndicator.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/ILSIndicator.js)**
  * added empty value check for `localizer`
- **[B747_8_FMC_MainDisplay.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_MainDisplay.js)**
  * fixed automatic LNAV/VNAV activation (should fix #160)
  * removed Coherent call for `AP_ALT_VAR_SET_ENGLISH`
- **[B747_8_FMC_NavRadioPage.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_NavRadioPage.js)**
  * changed initial cell display for VOR1 and VOR2 frequency
  * brought VOR1 and VOR2 ident display to live
  * SimVar value changed
  * parameter to `formatRunway` added
- **[B747_8_MDF.css](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.css)**
  * added styles for the VOR/ADF needles
  * `font size` and `text-anchor` adjusted for Distance and Unit of VOR/DME Navaids
- ~~**[B747_8_MFD.html](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/B747_8_MFD.html)**~~
  * ~~VOR/ADF needles added~~
- **[B747_8_PFD.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/PFD/B747_8_PFD.js)**
  * improved ILS localizer beacon find (??)
- **[SvgConstraintElement.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/Svg/SvgConstraintElement.js)**
  * adjusted to use `overdrawFactor` from a previous patch
- **[SvgWaypointElement.js](html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/MFD/Svg/SvgWaypointElement.js)**
  * adjusted to use `overdrawFactor` from a previous patch

### CODE REVIEW

**Comment by r4yman** [comment]
@747-4EVER please have a look at the VOR/ADF needles I think they look off

VOR_needles

**Comment by r4yman** [comment]
@iFarisKH I did as your **TODO** told me and removed the comments from your [code](https://github.com/saltysimulations/salty-747/blob/b91deb84aea11e49ef19da49e359b9f6eb702965/SimObjects/Airplanes/Asobo_B747_8i/model/747_8I_INTERIOR.xml#L1830-L1868). Please have a look if thats correct!

**Comment by 747-4EVER** [comment]
Those small needles on the bottom corners shouldn't exist on the 747, it's just something they ported over from the A320.

If you can delete the svg elements and fix the x-axis translation of the ADF/VOR L/R labels then it should be good.

Could you also try tuning a VOR and just see how the needles look when drawn on the map display?

Thanks

**Comment by ninjomcs** [comment]
> @iFarisKH I did as your **TODO** told me and removed the comments from your [code](https://github.com/saltysimulations/salty-747/blob/b91deb84aea11e49ef19da49e359b9f6eb702965/SimObjects/Airplanes/Asobo_B747_8i/model/747_8I_INTERIOR.xml#L1830-L1868). Please have a look if thats correct!

haven't heard from them in months, doubt you'll get a reply

**Comment by r4yman** [comment]
> > @iFarisKH I did as your **TODO** told me and removed the comments from your [code](https://github.com/saltysimulations/salty-747/blob/b91deb84aea11e49ef19da49e359b9f6eb702965/SimObjects/Airplanes/Asobo_B747_8i/model/747_8I_INTERIOR.xml#L1830-L1868). Please have a look if thats correct!
> 
> haven't heard from them in months, doubt you'll get a reply

Actually I made a mistake, seems like the code is from Asobo and git blame reported him because he initially copied the file. This means the code is not meant to be there yet.

**Comment by r4yman** [comment]
> Those small needles on the bottom corners shouldn't exist on the 747, the needles should only be drawn on the map compass itself when a station is tuned, it's just something they ported over from the A320.
> 
> If you can delete the svg elements and fix the x-axis translation of the ADF/VOR L/R labels then it should be good.
> 
> Could you also try tuning a VOR and just see how the needles look when drawn on the map display?
> 
> Thanks

Its weird but since I removed the two small needles in the bottom, nothing seems to show in these two corners anymore. And I dont know where the needles on the compass line come from in the stock game. Have they been there before?

**Comment by DesertRick13** [comment]
My note to Asobo (for those working on porting changes) These are observations of the just plain vanilla 747, not Salty's
 
There are a couple of observations I have about the most recent hotfix 1.14.6. Positively, it is much easier to change the route. I purposely plugged in a route and then changed it three different times. Instead of the flight plan looking like a bowl of spaghetti where routes would not change, but were added to, the route changed. And I didn't need to backtrack a hundred miles to start the approach. 
On the negative side, the update did not do a thing for the flaps in the 747. It still feels when flaps 5 is selected like hitting an arresting wire when approaching, and being launched when the flaps retract. And the flap drag effect does not feel proportional, but rather fully on or fully off. Lift feels more proportional, but drag does not. 
Also, the autopilot in the ILS approach has gone from decent to pretty useless. 
I appreciate the attempts. I just wish that the positive would be kept as well as the negative being fixed.

**Comment by hheexx** [comment]
@DesertRick13  I confirm everything except ILS. For me it's quite good most of the time but sometimes drops strangely bellow GS.

**Comment by DesertRick13** [comment]
@hheexx For me, the ILS diamonds were right on the money, but the APP function on the AP didn't hold, even though I set up for the approach properly before engaging. I hand fly the final 5nm anyway, but usually use the time from about 15nm to five to do checks before guiding her in.

**Comment by dcherrie** [comment]
Just did a flight testing fuel flow scalar change and using this candidate for the rest. Didn't really have any issues except the normal ones. Editing flight plan inflight becomes complicated and glitched where you cannot see the changes you have made to the route until you press ACTIVATE and EXECUTE. Will try doing a flight entering the flight plan fully manually next time.

Obviously one of the biggest problems is with Asobo and flaps issue when deployed at flaps 5 limiting the aircraft to less than 200-220 knots on take-off and landing.

Did a flight yesterday with the current development version and this seems to be much better in my opinion.

**Comment by ninjomcs** [comment]
is this ready to be merged

**Comment by DesertRick13** [comment]
When will the master reflect the merge?

**Comment by DesertRick13** [comment]
@r4yman; @ninjomcs, just left a comment in the help section. The latest modifications made by R4yman and Tyhi left glass cockpit blank. Not sure if there is something I'm not doing that I need to do, or if it is bugged. I don't appreciate that there is not a comment section in the latest branch, particularly when it states it's ready to be merged, and that one of the designers (Tyhi) cannot be contacted within the project.

**Comment by dcherrie** [comment]
> @r4yman; @ninjomcs, just left a comment in the help section. The latest modifications made by R4yman and Tyhi left glass cockpit blank. Not sure if there is something I'm not doing that I need to do, or if it is bugged. I don't appreciate that there is not a comment section in the latest branch, particularly when it states it's ready to be merged, and that one of the designers (Tyhi) cannot be contacted within the project.

I had an issue loading up last night which left the cockpit panels especially the ND in a weird state where the green banana was in the centre of screen, the top said TRK, all of the blue indicators were on for ARPT, WPT, WXR etc and the time to align the IRS was totally in the wrong spot with other text over the top of it. I couldn't align and nothing changed so reloaded and was all good.

**Comment by DesertRick13** [comment]
using this particular mod with WU4 was pretty positive
Pros: Fuel system, including stab and reserve tanks, worked.
         Flaps behavior seems much better, both takeoff and landing.
         no. 1 throttle is fixed.
         LNAV redirected well when I was assigned the runway after taking off. No spaghetti bowl of aborted flight plans. 


cons:   Lights in the fuel system buttons did not light, neither when the tanks had fuel nor when we should "press" to turn them 
           off. All other lights seemed normal.
           Parking brake indicator was lighted, but did not generate a caution.
Conclusion: I only flew about 20 minutes from TJSJ to TJBQ, manually altering fuel levels to trigger stab and reserve tanks. Do not know about high altitude behavior, nor consumption. Decently impressed with what I saw of the updates v/v 747 flight characteristics.

**Comment by hheexx** [comment]
Yea lot of fixes but still broken AUTOLAND often...

**Review by 747-4EVER — APPROVED** [review]

**Pull request merged**
