### PR TITLE
Fixed Fuel Burn

### PR DESCRIPTION
**Pull request by 747-4EVER**
Continued from #131.

Only changes Fuel Burn, all changes to thrust and Fuel Flow Displays have been reverted.

### CODE REVIEW

**Review by ninjomcs — APPROVED** [review]

**Comment by zakiack** [comment]
Name: zakiack#8247
Date of testing: Current date 03/07/2021
Version of the sim: 1.13.17.0
PR Tested: #155 

Testing technique: Performed a full flight from [OTHH - OPKC](https://github.com/saltysimulations/salty-747/files/6096899/OTHHOPKC_PDF_1615101587.pdf)

Steps you've made to test the Pull Request:
1.  Loaded into aircraft cold and dark
2.  Loaded aircraft with values from Simbrief OFP
3.  Monitored Fuel throughout the flight

Overall Rating: Good
Simbrief predicted I would land with 27.5 tons of fuel, and I landed with 23.8. The lower fuel could be due to me using the APU on the ground instead of the GPU, and had to extend my approach due to altitude. 

I can perform more flights later and can compare results.

**Comment by dcherrie** [comment]
Have done 6 more test flights with Test 8 to 10 being after Sim Update III. I don't believe there has been any changes by Asobo to do with fuel consumption or performance.

Looking at the following flights I have started looking at the fuel consumption per hour for each way point, the cruise and overall. The fuel burn in MSFS is linear and does not change with the weight of the aircraft which is what SimBrief accounts for.

Using a fuel scalar of 1.276, on average the fuel burn will be around 21,500 pounds per hour for cruise. The average for the real life 747-8 on average is 11,350 litres per hour which is 20,021 pounds per hour.

Unless we can change the programming so that fuel burn isn't linear aka burns more fuel when at the start of the flight when it's heavier compared to burning less fuel at the end of the flight when it's lighter, we will have to compromise.

On short-haul flights using this scalar, it is guaranteed you are going to burn up to a few more thousand pounds than planned, however flying long-haul, it will be a few thousand or tens of thousands over. It's a compromise but lowering the fuel scalar so short-haul flights are more accurate will mean that 3,000 pound difference on a short-haul will actually be potentially be several tens of thousands of pounds overweight when landing.

I currently think 1.276 is the best of both worlds for the mean time. You're not going to run out of fuel on a short haul, and you're not going to be overweight with landing on a long-haul.

[FFS Test 6 - KJFK to EGLL.pdf](https://github.com/saltysimulations/salty-747/files/6129786/FFS.Test.6.-.KJFK.to.EGLL.pdf)
[FFS Test 7 - WSSS to EGLL.pdf](https://github.com/saltysimulations/salty-747/files/6129787/FFS.Test.7.-.WSSS.to.EGLL.pdf)
[FFS Test 8 - NZAA to YSSY.pdf](https://github.com/saltysimulations/salty-747/files/6129788/FFS.Test.8.-.NZAA.to.YSSY.pdf)
[FFS Test 9 - OMDB to YSSY.pdf](https://github.com/saltysimulations/salty-747/files/6129789/FFS.Test.9.-.OMDB.to.YSSY.pdf)
[FFS Test 10 - WSSS to YSSY.pdf](https://github.com/saltysimulations/salty-747/files/6129790/FFS.Test.10.-.WSSS.to.YSSY.pdf)

**Comment by dcherrie** [comment]
Some more test flights with Test 12 and onwards with the updated flight dynamics after the flap hotfix from Asobo. Test 14 and 15 are using Pull Request #165 except with the change to Fuel Flow Scalar. 

Am happy with the consistent results especially in the cruise fuel burn error compared to short haul and long haul flights.

[FFS Test 11 - WSSS to EGLL.pdf](https://github.com/saltysimulations/salty-747/files/6251884/FFS.Test.11.-.WSSS.to.EGLL.pdf)
[FFS Test 12 - EGLL to KLAX.pdf](https://github.com/saltysimulations/salty-747/files/6251885/FFS.Test.12.-.EGLL.to.KLAX.pdf)
[FFS Test 13 - WSSS to EGLL.pdf](https://github.com/saltysimulations/salty-747/files/6251886/FFS.Test.13.-.WSSS.to.EGLL.pdf)
[FFS Test 14 - YSSY to YBBN.pdf](https://github.com/saltysimulations/salty-747/files/6251887/FFS.Test.14.-.YSSY.to.YBBN.pdf)
[FFS Test 15 - EGCC to CYVR.pdf](https://github.com/saltysimulations/salty-747/files/6251897/FFS.Test.15.-.EGCC.to.CYVR.pdf)

**Comment by DesertRick13** [comment]
RCTP-TJSJ including a descending spiral because of poor ATC instructions and a go-around because of poor ATC spacing.
Time in air: Approximately 17hr 15 min.
TOW 984k lbs
Fuel weight 421k lbs +/- (100 pct of capacity)
Fuel remaining approximately 50 k lbs.

Seemed a little thirsty, but looking at it on paper, it seems about right.

**Comment by k8cpachuck** [comment]
how long is it gonna be till this mod is finished? tried using the
beta and salty doesn't show up in the plane list.

**Comment by dcherrie** [comment]
> how long is it gonna be till this mod is finished? tried using the beta and salty doesn't show up in the plane list.
> […](#)
> On 4/7/21, DesertRick13 ***@***.***> wrote: RCTP-TJSJ including a descending spiral because of poor ATC instructions and a go-around because of poor ATC spacing. Time in air: Approximately 17hr 15 min. TOW 984k lbs Fuel weight 421k lbs +/- (100 pct of capacity) Fuel remaining approximately 50 k lbs. Seemed a little thirsty, but looking at it on paper, it seems about right. -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#155 (comment)](https://github.com/saltysimulations/salty-747/pull/155#issuecomment-815015380)

> how long is it gonna be till this mod is finished? tried using the beta and salty doesn't show up in the plane list.
> […](#)
> On 4/7/21, DesertRick13 ***@***.***> wrote: RCTP-TJSJ including a descending spiral because of poor ATC instructions and a go-around because of poor ATC spacing. Time in air: Approximately 17hr 15 min. TOW 984k lbs Fuel weight 421k lbs +/- (100 pct of capacity) Fuel remaining approximately 50 k lbs. Seemed a little thirsty, but looking at it on paper, it seems about right. -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#155 (comment)](https://github.com/saltysimulations/salty-747/pull/155#issuecomment-815015380)

Are you talking in regards to just the fuel burn, or the overall mod?

Once there is enough testing done for the quality assurance, then the fuel burn pull request will be added to the master. I've done enough testing on my end and in my opinion the pull request is ready but just needs testing from others as a pair of fresh eyes.

**Comment by k8cpachuck** [comment]
the entire mod. stock 747 sucks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dcherrie** [comment]
> the entire mod. stock 747 sucks

Ummm... theres a lot of work to do and we all volunteer our time here. If you're looking for a more finished product I'd suggest waiting for PMDG 747 which will be out in the next year or two. Until then, SALTY is just a stop-gap measure and we are making it the best we can.

**Comment by DesertRick13** [comment]
@k8cpachuck Did you place the salty version in the community folder? Most often, when it doesn't show up, that's why,

**Comment by k8cpachuck** [comment]
yessir, i did.

**Comment by BobbyFuzzy** [comment]
Name: BobbyFuzzy#4615
Date of testing: 14/04/2021
Version of the sim: 1.15.7.0
PR Tested: #155 
Object of test: Fuel flow
Testing technique: Conduct flight and monitor FF
Steps you've made to test the Pull Request:
1. Planned flight/routing on SimBrief (KJFK - EGLL)
2. Setup and conducted flight as normal. W/B as close to SB plan as possible
3. Monitored FF at intervals

Microsoft Flight Simulator 14_04_2021 12_14_16


Flight notes

Startup: Normal, except fuel pump push button decals were not visible/offset (see below)

Microsoft Flight Simulator 14_04_2021 12_20_34

Taxi/Takeoff : As normal

Cruise: Fuel flow initially seemed lower than expected then throughout the flight gradually became more than expected.
I did embarrassingly leave the APU on for most of the flight without noticing so this would have some bearing on the results. I shut this down before the descent. Otherwise all normal

Actual/expected in cruise:

- TOC 148/138.2
- VITOL 137/135.3
- NANSO 116.1/108.9
- EVRIN 32.7/35.9
- NIGIT 29.6/29.6

Descent/Landing : Normal

Shutdown: Landing fuel was 22.6 whilst expected was 27.5 so overall I think this is within a rough margin of error and much closer than default. 

Issues (If Any): Usual Asobo issues. MFD was always North up (see below), not sure if issue with this PR or not as not flown 747 default since this update.

Microsoft Flight Simulator 14_04_2021 12_36_15


Overall Rating: Good
Conclusions of the testing: Could do with some fine tuning to wind it back a touch, but not game-breaking and definitely workable

**Pull request merged**
