### PR TITLE
Progress Page 1

### PR DESCRIPTION
**Pull request by 747-4EVER**
**FMC progress page 1 mostly functional.**

**Features DTG, ETA and estimated fuel for:**
- Active Waypoint
- Next Waypoint
- Destination Airport

**DISTANCE TO GO**
Distance To Go calculated as direct from Aircraft to Active Waypoint, then calculated from cumulative Flight Plan distances for subsequent points.

**TIME**
Time estimates based on current measured ground speed (essentially accurate only for still air conditions).
Future improvements should improve accuracy when waypoint Wind Data and variable VNAV Cruise Speeds are available.
Individual profile speeds (CLB, CRZ, DES) will improve this further.

**FUEL ESTIMATES**
Fuel estimate based on current detected fuel flow and ETA as above.
Again will be improved with real aircraft data for variable CRZ speeds and levels.

**TOP OF DESCENT**
Calculates and displays predicted TOD based on Flight Crew Training Manual recommendations (again for still wind).
3.5NM distance per 1000 feet + 12NM for a level deceleration segment.
TOD displays when in the cruise and within 200NM of destination.

**MISC**
Also displays current commanded cruise speed (IAS or MACH).
Flight Number displays in page title.

### CODE REVIEW

**Comment by zakiack** [comment]
Name: zakiack#8247
Date of testing: Current date 20/12/2020
Version of the sim: The Version that I got from clicking on https://github.com/747-4EVER/salty-747/tree/Progress-page then clicking "code" then "Download ZIP"
PR Tested: #115

Testing technique: Did a full flight from OPLA - OPKC via MIMA2D MIMAL J112 NH NH2B. Monitored progress page throughout
Steps you've made to test the Pull Request:
1.  Set up aircraft from cold and dark for flight
2.  Monitored and took screenshots of Progress Page throughout flight (Before Departure, Climb, Cruise, Descent)
3.  Compared with features mentioned in description of PR

Overall Rating: Good
Conclusions of the testing: The progress page works as it should displaying the fuel calculations and distance. Fuel Predictions were accurate within +-0.2 from 80nm away from waypoint. Predictions were much more accurate the closer to the waypoint. Distance was accurate, however distance on ND seems to be rounded differently so they sometimes disagree by about 1nm. This is a very minor issue.
Screenshot_453

**Review by ninjomcs — APPROVED** [review]

**Comment by zakiack** [comment]
Name: zakiack#8247
Date of testing: Current date 05/01/2021
Version of the sim: Version the tester uses
PR Tested: #115 

Testing technique: Performed a flight from cold and dark from OPLA to OMBD via MIMA2D MIMAL G214 PG G665 ASVIB N312 MOBET M324 PATAT L519 PUVAL PUVA2E
Steps you've made to test the Pull Request:
1.  Performed flight
2.  Monitored progress page throughout flight

Overall Rating: Good
Overall the progress page is pretty good
Only issue I saw was that the T/D calculations did not appear within 200nm of the destination
This could be due to me stepping from FL360 to FL370 causing the aircraft to get confused about which flight phase I was in. Even when I was descending the aircraft seemed to think I was in CLB
Screenshot below showcases issue
Screenshot_478

**Comment by ninjomcs** [comment]
> Only issue I saw was that the T/D calculations did not appear within 200nm of the destination

That is actually intended, as described in the PR

**Comment by valenzz2004** [comment]
Category: QA Tester
Name: Valenzz2004#7802
Date of testing: 06/01/2021
Version of the sim: 1.12.13.0
PR Tested: #115 
Object of test: test the progress page

Testing technique: cross atlantic long haul
Steps you've made to test the Pull Request:

1. spawned at KORD and did flight plan
2. planned weights and pushed back
3. departed and began to follow route 
4. executed three step climbs in north america updating vnav page every time
5. used progress page for my oceanic clearance and position reports
6. entered european airspace and continued to ELLX as planned
7. T/D worked fine and gave appropriate place to start descent
8. landed into ELLX

Flight notes (If required): ROUTE KORD/28R DCT EBAKE DCT WISMO DCT POSTS DCT PADDE DCT SVM Q907 SIKBO
Q905 IPTOS Q921 AGLUK DCT BAREE N505A RIKAL NATZ BEXET DCT BAKUR
N546 STU UL9 KONAN UL607 REMBA REMBA3M ELLX/24

Issues (If Any):
Overall Rating: Great
Conclusions of the testing: worked perfectly and helped me on my oceanic clearance on vatsim for my atlantic crossing
Screenshots( if any):

**Pull request merged**
