### PR TITLE
 Ported Progress Features to Asobo base page

### PR DESCRIPTION
**Pull request by 747-4EVER**
Features from the previous progress page 1 implementation have been ported using the asobo default page as a base.

Differences from Asobo default include:
- Added ATC callsign to page title
- All ETAs now adjusted from local time to UTC
- Fuel estimates display to nearest 100lbs
- Added SEL SPD field showing current command speed or Mach
- Changed Layout to match real aircraft
- Deleted incorrect fields not present on real aircraft 

Note: T/D function has been disabled due to inaccuracies & needing improvement to logic.
Note: Active Waypoint should display Magenta, however Fmc.SetLine function does not seem to accept this as a valid colour.

FCOM Reference:
image

### CODE REVIEW

**Review by ninjomcs — APPROVED** [review]

**Comment by valenzz2004** [comment]
Category: QA Tester
Name: Valenzz2004#7802
Date of testing: 17/01/2021
Version of the sim: 1.12.13.0
PR Tested: #130 
Object of test: check functionality of the new prog page

Testing technique: climb to cruise and check timings and distances along the cruise 
Steps you've made to test the Pull Request:

1. loaded in C/D at EGLL and set up for an IFR flight to EGCC
2. taxied and departed 27R
3. climbed to cruise and did time and distance checks on waypoints 

Time Checks (this is based on the in game UTC) 

T/C
1st CRZ waypoint WOBUN  Time in prog estimate: 1341 Time upon reaching: 1341
2nd CRZ waypoint WELIN   Time in prog estimate: 1343 Time upon reaching: 1343
3rd CRZ waypoint AKUPA   Time in prog estimate: 1346 Time upon reaching: 1345
4th CRZ waypoint TIMPO   Time in prog estimate: 1347 Time upon reaching: 1346
Last CRZ waypoint ELVOS   Time in prog estimate: 1348 Time upon reaching: 1348
T/D

Flight notes (If required): Route EGLL/27R UMLA1F UMLAT T418 WELIN T420 TNT DAYN2A EGCC/23L CRZ: FL190 MACH: .70

Issues (If Any): DTG was accurate at all times however i cannot give a perspective on long distances between waypoints as that would require some time 
Overall Rating: Good 
Conclusions of the testing: works as planned and as far as I could see there was absolutely no issues with the timings or the distance and everything on the page was in the right place :)
Screenshots( if any):

**Comment by BobbyFuzzy** [comment]
Name: BobbyFuzzy#4615
Date of testing: Current date 19/01/2020
Version of the sim: 1.12.13.0
PR Tested: #130 
Object of test: (ECAM Page or Flight model or views or anything, what the PR modifies)

Testing technique: Spawn cold & dark, execute full flight from start to finish
Steps you've made to test the Pull Request:
1. Spawn cold and dark, weights set in main menu, 3rd party livery
2. Startup aircraft and enter FPLN manually
3. Execute flight whilst monitoring PROG page

Flight notes

Startup: All OK

Taxi/Takeoff :  All OK

Cruise: DTG to destination stops updating after a while (see below screenshot)

Descent/Landing: DTG did not re-adjust when adding STAR to flight plan (added whilst airborne), just showed direct distance to destination

Microsoft Flight Simulator 19_01_2021 14_40_16

Shutdown: All OK

Issues (If Any): Does not update when adding a STAR to flight plan
Overall Rating: OK - issues with STAR perhaps Asobo related?
Conclusions of the testing: Would like to see DTG to destination continue to update throughout

**Comment by 747-4EVER** [comment]
> Name: BobbyFuzzy#4615
> Date of testing: Current date 19/01/2020
> Version of the sim: 1.12.13.0
> PR Tested: #130
> Object of test: (ECAM Page or Flight model or views or anything, what the PR modifies)
> 
> Testing technique: Spawn cold & dark, execute full flight from start to finish
> Steps you've made to test the Pull Request:
> 
> 1. Spawn cold and dark, weights set in main menu, 3rd party livery
> 2. Startup aircraft and enter FPLN manually
> 3. Execute flight whilst monitoring PROG page
> 
> Flight notes
> 
> Startup: All OK
> 
> Taxi/Takeoff : All OK
> 
> Cruise: DTG to destination stops updating after a while (see below screenshot)
> 
> Descent/Landing: DTG did not re-adjust when adding STAR to flight plan (added whilst airborne), just showed direct distance to destination, note FMS did not let me insert full STAR - only the transition so this is probably worth testing on another airport/approach (which I will try in due course and add another comment)
> 
> Microsoft Flight Simulator 19_01_2021 14_40_16
> 
> Shutdown: All OK
> 
> Issues (If Any): Does not update when adding a STAR to flight plan
> Overall Rating: OK - issues with STAR perhaps Asobo related?
> Conclusions of the testing: Would like to see DTG to destination continue to update throughout

Latest commit should fix DTG calculation due to Asobo oversight.

**Comment by BobbyFuzzy** [comment]
Retested on same flight, DTG now working as expected.

**Comment by arnaumj** [comment]
Name: arnaumj#3072
Date of testing: Current date 02/12/2020
Version of the sim: 1.12.13.0
PR Tested: #130
Object of test: Auto pilot,Simbrief integration, PR #130 

Testing technique: Spawn cold & dark, execute full flight from start to finish
Steps you've made to test the Pull Request:

Spawn cold and dark, Selected weights from simbrief
Startup aircraft and enter FPLN manually
Execute flight whilst monitoring PROG page,and VNAV
Flight notes

Startup: All OK

Taxi/Takeoff : All OK (Although we took off in a literal hurricane)

Cruise: All fine and at cruise we turned off 2 engines as a test and they started up ,something else that  I did test was the APU it should not be able to run at FL360

Descent/Landing: Programmed the FMC to run a star and it runned the star ,ILS approach into Tokyo 34R was not functioning had to manually approach (it could not do heading and approach)

Conclusion of testing: Simbrief integration was a little bit buggy because it gave me errors such as "NOT IN DATABASE" .Autopilot was functioning phenomenally during Cat 3 conditions. Autopilot needs work. DTG was functioning and accurate.

**Comment by CharlieAlphaLima** [comment]
Name: CharlieAlphaLima#1446
Date of testing: Current date 12/02/2021
Version of the sim: 1.12.13.0
PR Tested: #130

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Load sim
2. C/D Live time/Weather
3 Startup aircraft in usual fashion, inserting flightplan manually 
4 Departure out of PANC up until cruise
5 Unable to complete full flight due to time.


Looks to be the the right FMC is unresponsive to input. Only left FMC is working.
PROG page is frozen when left on. Have to click off then back onto PROG page for the figures to update
Simbreif intergration had issues. Unable to load flightplan (had to do manually) 

Overall Rating: Good/ PROG page function as stated in the pull request bar isuue raised above. 
Distance calculations work as expected. All times are matching that of the fmc. DTG all accurate

**Comment by ninjomcs** [comment]
the right fmc thing is a bug in the default 748.

**Comment by MatiasTR** [comment]
Name: Matias ◢◤#52940
Date of testing: 12/02/2021
Version of the sim: 1.12.13.0
PR Tested: #130

Normal flight SAZS -> X -> SAEZ
1. Loaded FLPN from MSFS planner directly (SAZS -> SAZR
2. Compared estimated times and distances with real ones
3. Changed flight plan in the middle of the flight
4. Repeated step 2

Overall Rating: Good
Conclusions of the testing: The system behaved as expected without errors.

**Comment by zakiack** [comment]
Name: zakiack#8247
Date of testing: Current date 13/2/2021
Version of the sim: 1.12.13.0
PR Tested: #130 

Testing technique: Performed a flight from OPKC - OPLA while monitoring progress page religiously
Steps you've made to test the Pull Request:
1. Loaded into aircraft cold and dark
2. Setup aircraft and FMC for flight
3. Departed while monitoring progress page (DTG especially)
4. Flew while monitoring progress page

Overall Rating: ok
I noticed the issue with the DTG where it changes in weird ways during the flight.

https://user-images.githubusercontent.com/76414253/107862680-1e76ee00-6e03-11eb-8c7f-6ea53533f48e.mp4

Looking at the video above, when I reach BADUL, the DTG goes up by 1nm. This is rather miniscule, but on longer flights such as mentioned below, this seems to add up. 

Screenshot_523

I'm planning on doing a long haul later today, and can fill out another test on my observations then, as well.

**Comment by zakiack** [comment]
> Name: zakiack#8247
> Date of testing: Current date 13/2/2021
> Version of the sim: 1.12.13.0
> PR Tested: #130
> 
> Testing technique: Performed a flight from OPKC - OPLA while monitoring progress page religiously
> Steps you've made to test the Pull Request:
> 
> 1. Loaded into aircraft cold and dark
> 2. Setup aircraft and FMC for flight
> 3. Departed while monitoring progress page (DTG especially)
> 4. Flew while monitoring progress page
> 
> Overall Rating: ok
> I noticed the issue with the DTG where it changes in weird ways during the flight.
> 
>  Microsoft.Flight.Simulator.2021.02.13.-.12.24.18.02.DVR_Trim.mp4 
> Looking at the video above, when I reach BADUL, the DTG goes up by 1nm. This is rather miniscule, but on longer flights such as mentioned below, this seems to add up.
> 
> Screenshot_523
> 
> I'm planning on doing a long haul later today, and can fill out another test on my observations then, as well.

After further testing, it seems the issue with the DTG is in Asobo's default progress page, rather than the Salty progress page.
When flying from PANC - KRIV, no such problems were found with the DTG

**Pull request merged**
